// GENERATED by scripts/generate_pet_sprites.mjs — do not edit by hand.
// Re-run `node scripts/generate_pet_sprites.mjs` after editing the art.

export const PET_FRAME = 16;
export const PET_SHEET_COLS = 4;
export const PET_SHEET_ROWS = 9;

export type PetAnimKey =
  | "idle"
  | "walk"
  | "work"
  | "celebrate"
  | "concerned"
  | "doze"
  | "happy"
  | "teleout"
  | "telein";

export interface PetAnim { row: number; frames: number; fps: number }

export const PET_ANIMS: Record<PetAnimKey, PetAnim> = {
  idle: { row: 0, frames: 2, fps: 1.2 },
  walk: { row: 1, frames: 2, fps: 5 },
  work: { row: 2, frames: 2, fps: 4 },
  celebrate: { row: 3, frames: 4, fps: 6 },
  concerned: { row: 4, frames: 2, fps: 2 },
  doze: { row: 5, frames: 1, fps: 1 },
  happy: { row: 6, frames: 2, fps: 4 },
  teleout: { row: 7, frames: 4, fps: 10 },
  telein: { row: 8, frames: 4, fps: 10 },
};

export interface PetSpeciesDef {
  sheet: string;
  /** Frame-space point the hat overlay is centred on (hat sits above it). */
  hatAnchor: { x: number; y: number };
  /** Silhouette-specific anchors: the curled doze and crouched celebrate
   *  poses carry the head much lower than the standing pose. */
  hatAnchorDoze: { x: number; y: number };
  hatAnchorCelebrate: { x: number; y: number };
  /** Display name used as the default pet name. */
  defaultName: string;
}

export const PET_SPECIES: Record<"cat" | "axolotl" | "robot", PetSpeciesDef> = {
  cat: { sheet: "/pets/cat.png", hatAnchor: { x: 8, y: 2 }, hatAnchorDoze: { x: 8, y: 8 }, hatAnchorCelebrate: { x: 8, y: 5 }, defaultName: "Mochi" },
  axolotl: { sheet: "/pets/axolotl.png", hatAnchor: { x: 8, y: 3 }, hatAnchorDoze: { x: 8, y: 8 }, hatAnchorCelebrate: { x: 8, y: 6 }, defaultName: "Bloop" },
  robot: { sheet: "/pets/robot.png", hatAnchor: { x: 8, y: 1 }, hatAnchorDoze: { x: 8, y: 6 }, hatAnchorCelebrate: { x: 8, y: 4 }, defaultName: "Bolt" },
};

export const PET_HATS = {
  sheet: "/pets/hats.png",
  frame: 16,
  keys: ["party", "headphones", "wizard", "crown"] as const,
};

export type PetHatKey = (typeof PET_HATS.keys)[number];

/** Lowest art row of each hat within its 16×16 frame — runtime raises
 *  each hat so this row lands on the species hatAnchor.y. */
export const PET_HAT_BOTTOM: Record<PetHatKey, number> = {
  party: 8,
  headphones: 7,
  wizard: 9,
  crown: 9,
};
