// A single chat message bubble. User messages right-aligned, assistant
// left-aligned. Renders markdown via react-markdown with syntax highlighting.
// Streaming token-by-token updates are debounced to ~50ms by the caller —
// this component simply accepts a `content: string` prop and renders it.
import { useCallback, useMemo, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import "katex/dist/katex.min.css";
import type { ChatMessage } from "../../lib/ipc";
import type { ChatArtifact } from "../../state/chat";
import { parseUnifiedDiff } from "../../lib/diff";
import { InlineDiagram } from "./InlineDiagram";
import { MermaidDiagram } from "./MermaidDiagram";
import { MessageAttachments, parseAttachments } from "./MessageAttachments";

interface Props {
  message: ChatMessage;
  /** True for the in-progress streaming bubble — hides the action bar. */
  live?: boolean;
  /** When provided (user messages), shows an "Edit" action that loads the
   *  message text back into the composer. */
  onEdit?: (content: string) => void;
  /** When provided (assistant messages), shows a "Regenerate" action. */
  onRepeat?: () => void;
  /** Artifacts generated by this message, shown as clickable chips below it. */
  artifacts?: ChatArtifact[];
  /** Open an artifact in the preview pane (used by the inline chips). */
  onPreviewArtifact?: (artifact: ChatArtifact) => void;
}

// --- Inline SVG icons (Claude-style, stroke-based, currentColor). ---
const iconProps = {
  width: 15,
  height: 15,
  viewBox: "0 0 24 24",
  fill: "none",
  stroke: "currentColor",
  strokeWidth: 2,
  strokeLinecap: "round" as const,
  strokeLinejoin: "round" as const,
};

function CopyIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <rect x="9" y="9" width="13" height="13" rx="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

function CheckIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <path d="M20 6 9 17l-5-5" />
    </svg>
  );
}

function EditIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <path d="M12 20h9" />
      <path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4Z" />
    </svg>
  );
}

function RepeatIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <path d="M3 2v6h6" />
      <path d="M3 13a9 9 0 1 0 3-7.7L3 8" />
    </svg>
  );
}

function FileIcon() {
  return (
    <svg
      width={13}
      height={13}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>
  );
}

/** Download/preview chip for a generated file. */
function ArtifactChip({
  artifact,
  onPreviewArtifact,
}: {
  artifact: ChatArtifact;
  onPreviewArtifact?: (artifact: ChatArtifact) => void;
}) {
  return (
    <button
      type="button"
      className="chat-artifact-chip"
      title={`Preview ${artifact.filename}`}
      onClick={(e) => {
        e.currentTarget.blur();
        onPreviewArtifact?.(artifact);
      }}
    >
      <FileIcon />
      <span>{artifact.filename}</span>
    </button>
  );
}

/** The files an assistant message produced. .html/.svg artifacts are probed via
 *  InlineDiagram, which renders ONLY true diagrams (kind "diagram", authored by
 *  generate_diagram) inline; a plain .html webpage or .svg image falls back to
 *  a download chip so it opens in the preview pane instead. Every other file is
 *  always a download chip. */
function MessageArtifacts({
  artifacts,
  onPreviewArtifact,
}: {
  artifacts: ChatArtifact[];
  onPreviewArtifact?: (artifact: ChatArtifact) => void;
}) {
  const isVisual = (name: string) => {
    const ext = name.split(".").pop()?.toLowerCase();
    return ext === "html" || ext === "svg";
  };
  const chips = artifacts.filter((a) => !isVisual(a.filename));
  const visuals = artifacts.filter((a) => isVisual(a.filename));
  return (
    <>
      {visuals.map((a) => (
        <InlineDiagram
          key={a.path}
          artifact={a}
          onFallback={() => (
            <div className="chat-msg-artifacts">
              <ArtifactChip artifact={a} onPreviewArtifact={onPreviewArtifact} />
            </div>
          )}
        />
      ))}
      {chips.length > 0 && (
        <div className="chat-msg-artifacts" aria-label="Generated files">
          {chips.map((a) => (
            <ArtifactChip key={a.path} artifact={a} onPreviewArtifact={onPreviewArtifact} />
          ))}
        </div>
      )}
    </>
  );
}

/** Per-message action bar (Claude-style icons): copy for every message, edit
 *  for user messages, regenerate for assistant messages. Appears on hover
 *  under the bubble. */
function MessageActions({
  content,
  onEdit,
  onRepeat,
}: {
  content: string;
  onEdit?: (content: string) => void;
  onRepeat?: () => void;
}) {
  const [copied, setCopied] = useState(false);
  const copy = useCallback(
    async (e: React.MouseEvent<HTMLButtonElement>) => {
      // Drop focus so the hover-only action bar doesn't stay pinned open
      // after a mouse click.
      e.currentTarget.blur();
      try {
        await navigator.clipboard.writeText(content);
        setCopied(true);
        setTimeout(() => setCopied(false), 1800);
      } catch {
        // Clipboard unavailable — silently ignore.
      }
    },
    [content],
  );

  return (
    <div className="chat-msg-actions">
      <button
        className="chat-msg-action"
        onClick={copy}
        title={copied ? "Copied" : "Copy message"}
        aria-label="Copy message"
      >
        {copied ? <CheckIcon /> : <CopyIcon />}
      </button>
      {onRepeat && (
        <button
          className="chat-msg-action"
          onClick={(e) => {
            e.currentTarget.blur();
            onRepeat();
          }}
          title="Regenerate response"
          aria-label="Regenerate response"
        >
          <RepeatIcon />
        </button>
      )}
      {onEdit && (
        <button
          className="chat-msg-action"
          onClick={(e) => {
            e.currentTarget.blur();
            onEdit(content);
          }}
          title="Edit message"
          aria-label="Edit message"
        >
          <EditIcon />
        </button>
      )}
    </div>
  );
}

/** Codex-style pre-token indicator: a single quiet monospace pulse — no
 *  bouncing dots, just a subtle "working…" line that recedes visually. */
export function TypingIndicator() {
  return (
    <div className="chat-bubble assistant">
      <div className="chat-bubble-inner">
        <div className="chat-typing" aria-label="Assistant is responding" role="status">
          <span className="chat-typing-prompt">›</span>
          <span className="chat-typing-cursor" />
        </div>
      </div>
    </div>
  );
}

/** Low-weight, tappable marker shown in the timeline where older context was
 *  condensed by the local-model compaction framework. Expands to reveal the
 *  actual summary that replaced the original turns. Reuses the muted aesthetic
 *  of `.chat-status-notice` / `.chat-activity-done`. */
function CompactedContextMarker({ summary }: { summary: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="chat-compacted-marker">
      <button
        type="button"
        className="chat-compacted-toggle"
        aria-expanded={open}
        onClick={() => setOpen((v) => !v)}
      >
        <span className="chat-compacted-dash" aria-hidden="true">—</span>
        earlier context compacted
        <span className={`chat-thinking-chevron${open ? " open" : ""}`}>›</span>
      </button>
      {open && summary && (
        <div className="chat-compacted-summary">{summary}</div>
      )}
    </div>
  );
}

/** A tool-call process step emitted by the backend as `<tool>{json}</tool>`. */
interface ToolData {
  kind?: string;
  title?: string;
  detail?: string;
  lang?: string;
  code?: string;
  /** Optional result text rendered once the call completes. The backend
   *  doesn't populate this today (tool output is summarized by the model in
   *  the following narration), but the expandable step detail shows args/code
   *  regardless — `result` is reserved so a future backend field flows
   *  straight into the same disclosure. */
  result?: string;
}

type Segment =
  | { type: "text"; text: string }
  | { type: "think"; text: string; done: boolean }
  | { type: "tool"; data: ToolData | null; done: boolean };

/** Split an assistant message into ordered segments: plain markdown text,
 *  `<think>` reasoning blocks, and `<tool>` process cards. A block whose
 *  closing tag hasn't streamed in yet is marked `done: false`. */
function parseSegments(content: string): Segment[] {
  const segs: Segment[] = [];
  let rest = content;
  const tagRe = /<(think|tool)>/;
  for (;;) {
    const m = tagRe.exec(rest);
    if (!m) {
      if (rest) segs.push({ type: "text", text: rest });
      break;
    }
    const before = rest.slice(0, m.index);
    if (before) segs.push({ type: "text", text: before });

    const tag = m[1];
    const afterOpen = rest.slice(m.index + m[0].length);
    const close = `</${tag}>`;
    const ci = afterOpen.indexOf(close);
    const inner = ci === -1 ? afterOpen : afterOpen.slice(0, ci);
    const done = ci !== -1;

    if (tag === "think") {
      segs.push({ type: "think", text: inner.trim(), done });
    } else {
      let data: ToolData | null = null;
      try {
        data = JSON.parse(inner) as ToolData;
      } catch {
        data = null;
      }
      segs.push({ type: "tool", data, done });
    }

    if (ci === -1) break;
    rest = afterOpen.slice(ci + close.length);
  }
  return segs;
}

function ThinkingBlock({ thinking, done }: { thinking: string; done: boolean }) {
  const [open, setOpen] = useState(false);
  return (
    <div className={`chat-thinking${done ? "" : " live"}`}>
      <button
        className="chat-thinking-toggle"
        onClick={() => setOpen((o) => !o)}
        title={open ? "Hide thinking" : "Show thinking"}
      >
        <span className="chat-thinking-icon">›</span>
        {done ? "Thinking" : "Thinking…"}
      </button>
      {open && <div className="chat-thinking-body">{thinking}</div>}
    </div>
  );
}

/** Minimal text glyph for a tool step, keyed by the backend-provided `kind`.
 *  Uses monochrome symbols instead of colorful emoji for the Codex aesthetic. */
function toolGlyph(kind?: string): string {
  switch (kind) {
    case "search":
      return "◦";
    case "web":
      return "◦";
    case "browser":
      return "◦";
    case "file":
    case "code":
      return "◦";
    default:
      return "◦";
  }
}

/** A short, *specific* label for one tool step — rendered in monospace like a
 *  terminal log entry. The backend emits a generic `title` ("Reading a web page",
 *  "Searching the web") but also a `detail` carrying the actual target (url /
 *  query / filename). We prefer the detail so each step reads as what it
 *  actually touched, falling back to the title only when no detail is available.
 *  Format: `command  target` (two-space separation, log-style). */
function stepLabel(data: ToolData | null): string {
  if (!data) return "working…";
  const title = data.title?.trim() || "working…";
  const detail = data.detail?.trim();
  if (!detail) return title;
  // For code-producing tools the "detail" is sometimes the full code body —
  // too long for a row label; in that case keep the title.
  if (data.code && detail.length > 80) return title;
  // Log-style: "write_file  src/main.rs" rather than "Writing file — src/main.rs"
  const cmd = title.toLowerCase().replace(/\s+/g, "_").replace(/ing$/, "");
  return `${cmd}  ${detail}`;
}

/** A one-line synthesized summary of what a whole tool-call group accomplished.
 *  Generated client-side from the step set — minimal, log-like, monochrome.
 *  Quality is a judgment call (PRD §13); prefer specifics from `detail`. */
function summarizeGroup(steps: ActivityStep[]): string {
  if (steps.length === 0) return "working…";

  // If any step generated a file/document/diagram, lead with what was produced.
  const produced = steps.find(
    (s) => s.data?.kind === "file" || s.data?.kind === "code",
  );
  if (produced?.data?.title) {
    const producedCount = steps.filter(
      (s) => s.data?.kind === "file" || s.data?.kind === "code",
    ).length;
    const base = produced.data.detail?.trim() || produced.data.title;
    return producedCount > 1
      ? `${producedCount} files  ${base}`
      : base;
  }

  // Research-style runs: searches + page reads.
  const searches = steps.filter((s) => s.data?.kind === "search").length;
  const reads = steps.filter((s) => s.data?.kind === "web").length;
  const browser = steps.filter((s) => s.data?.kind === "browser").length;
  if (searches && reads) {
    return `${reads} page${reads > 1 ? "s" : ""}  ${searches} query${searches > 1 ? "ies" : "y"}`;
  }
  if (searches) return `${searches} query${searches > 1 ? "ies" : "y"}`;
  if (reads) return `${reads} page${reads > 1 ? "s" : ""}`;
  if (browser) return `${browser} browser step${browser > 1 ? "s" : ""}`;

  // Generic fallback.
  const toolNames = new Set(
    steps.map((s) => s.data?.title).filter(Boolean) as string[],
  );
  if (toolNames.size === 1) return [...toolNames][0];
  return `${steps.length} steps`;
}

/** Detect whether a string looks like a unified diff. */
function looksLikeDiff(text: string): boolean {
  return text.startsWith("diff --git") || text.startsWith("--- ") || text.includes("\n@@ ");
}

/** Render a unified diff inline inside a tool step body. Reuses the existing
 *  diff parser and CSS classes for a terminal-native look. */
function InlineDiff({ diffText }: { diffText: string }) {
  const files = useMemo(() => parseUnifiedDiff(diffText), [diffText]);
  if (files.length === 0) return <div className="chat-step-detail">{diffText}</div>;
  return (
    <div className="chat-diff-inline">
      {files.map((file, i) => (
        <div className="diff-file" key={`${file.newPath || file.oldPath || i}-${i}`}>
          <div className="diff-file-header">
            {file.oldPath === file.newPath || file.newPath === ""
              ? file.oldPath || file.newPath || `file ${i + 1}`
              : `${file.oldPath} → ${file.newPath}`}
          </div>
          {file.lines
            .filter((l) => l.type !== "meta")
            .map((line, j) => (
              <div key={j} className={`diff-line ${line.type}`}>
                {line.type === "add" ? "+ " : line.type === "del" ? "- " : line.type === "hunk" ? "" : "  "}
                {line.text}
              </div>
            ))}
        </div>
      ))}
    </div>
  );
}

/** A single tool-call row inside an expanded ActivitySummary. Renders the
 *  step's type icon + a specific label (the actual URL/query/filename, not a
 *  repeated generic title). Any narration text the model produced around
 *  this step is folded into the row above/below the label. The whole row is
 *  itself expandable (a second, nested disclosure) to reveal full detail:
 *  exact tool kind, detail string, and the code block for code-producing
 *  tools. File edits that contain a unified diff render as an inline diff. */
function ActivityStepRow({
  step,
  done,
  index,
}: {
  step: ActivityStep;
  done: boolean;
  index: number;
}) {
  const [open, setOpen] = useState(false);
  const hasBody = Boolean(
    step.data?.code || step.data?.detail || step.data?.result,
  );
  return (
    <div className={`chat-step${done ? "" : " live"}`}>
      <button
        className="chat-step-toggle"
        onClick={() => hasBody && setOpen((o) => !o)}
        title={hasBody ? (open ? "Hide details" : "Show details") : undefined}
        disabled={!hasBody}
      >
        <span className="chat-step-index">{index + 1}</span>
        <span className="chat-step-icon">{toolGlyph(step.data?.kind)}</span>
        <span className="chat-step-label">{stepLabel(step.data)}</span>
        {hasBody && (
          <span className={`chat-thinking-chevron${open ? " open" : ""}`}>›</span>
        )}
      </button>
      {step.before && step.before.trim().length > 0 && (
        <div className="chat-step-narration">{step.before}</div>
      )}
      {open && hasBody && (
        <div className="chat-step-body">
          {step.data?.detail && (
            <div className="chat-step-detail">{step.data.detail}</div>
          )}
          {step.data?.code && (
            looksLikeDiff(step.data.code) ? (
              <InlineDiff diffText={step.data.code} />
            ) : (
              <div className="chat-code-block">
                <div className="chat-code-header">
                  <span className="chat-code-lang">{step.data.lang || "text"}</span>
                  <CopyButton code={step.data.code} />
                </div>
                <SyntaxHighlighter
                  style={{}}
                  language={step.data.lang || "text"}
                  PreTag="div"
                  customStyle={{
                    margin: 0,
                    background: "transparent",
                    padding: "12px 16px",
                    fontSize: "12px",
                    fontFamily: "var(--font-mono)",
                    lineHeight: 1.5,
                    overflowX: "auto",
                  }}
                  codeTagProps={{ style: { fontFamily: "var(--font-mono)" } }}
                >
                  {step.data.code}
                </SyntaxHighlighter>
              </div>
            )
          )}
          {step.data?.result && (
            looksLikeDiff(step.data.result) ? (
              <InlineDiff diffText={step.data.result} />
            ) : (
              <div className="chat-step-result">{step.data.result}</div>
            )
          )}
        </div>
      )}
      {step.after && step.after.trim().length > 0 && !open && (
        <div className="chat-step-narration">{step.after}</div>
      )}
    </div>
  );
}

/** One collapsed activity group: a synthesized one-line summary of what the
 *  whole turn accomplished, expandable into the ordered step list. Tool steps
 *  render as ActivityStepRow (each itself further expandable); think steps
 *  render as compact nested ThinkingBlocks. A "Done" checkmark appears once
 *  the run has no live step remaining.
 *
 *  Grouping boundary: the caller folds the turn's ENTIRE tool activity —
 *  including thinking interludes — into this one container, so a multi-step
 *  task takes up a single collapsed row by default. A trailing plain-text
 *  answer renders outside this block. */
function ActivitySummary({ group }: { group: ActivityGroup }) {
  const [open, setOpen] = useState(false);
  const live = group.steps.some((s) => !s.done);
  const summary = summarizeGroup(group.steps);
  return (
    <div className={`chat-activity${live ? " live" : ""}`}>
      <button
        className="chat-activity-toggle"
        onClick={() => setOpen((o) => !o)}
        title={open ? "Collapse activity" : "Show activity steps"}
      >
        <span className="chat-activity-icon" aria-hidden="true">
          {live ? <span className="chat-activity-spinner" /> : "◦"}
        </span>
        <span className="chat-activity-summary">{live ? "working…" : summary}</span>
        <span className={`chat-thinking-chevron${open ? " open" : ""}`}>›</span>
        <span className="chat-activity-count">{group.steps.length}</span>
      </button>
      {open && (
        <div className="chat-activity-steps">
          {group.steps.map((step, i) =>
            step.think != null ? (
              <div className="chat-step-think" key={i}>
                {step.before && step.before.trim().length > 0 && (
                  <div className="chat-step-narration">{step.before}</div>
                )}
                <ThinkingBlock thinking={step.think} done={step.done} />
              </div>
            ) : (
              <ActivityStepRow
                key={i}
                step={step}
                done={step.done}
                index={i}
              />
            ),
          )}
          {!live && group.steps.length > 0 && (
            <div className="chat-activity-done">
              <span>—</span> done
            </div>
          )}
        </div>
      )}
    </div>
  );
}

/** Returns a style object for inline code elements using CSS variable lookups
 *  that work in both light and dark themes (the variables resolve at runtime). */
function useInlineCodeStyle() {
  return useMemo(
    () => ({
      background: "var(--surface-2)",
      padding: "2px 6px",
      borderRadius: "var(--radius-xs)",
      fontFamily: "var(--font-mono)",
      fontSize: "0.9em",
      boxShadow: "var(--glass-rim-soft)",
    }),
    [],
  );
}

function CopyButton({ code }: { code: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      // Clipboard unavailable — silently ignore.
    }
  }, [code]);

  return (
    <button className="ghost copy-code-btn" onClick={handleCopy}>
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

/** djb2 — a tiny stable hash so a JSX block gets a consistent preview id. */
function hashCode(s: string): string {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) | 0;
  return (h >>> 0).toString(36);
}

/** Chip that opens a ```jsx / ```tsx block as a live preview in the side pane
 *  (Claude-style), instead of rendering it inline in the chat. */
function JsxArtifactChip({
  code,
  lang,
  onPreviewArtifact,
}: {
  code: string;
  lang: "jsx" | "tsx";
  onPreviewArtifact?: (artifact: ChatArtifact) => void;
}) {
  const filename = `Component.${lang}`;
  return (
    <button
      type="button"
      className="chat-artifact-chip chat-jsx-chip"
      title="Open live React preview"
      onClick={(e) => {
        e.currentTarget.blur();
        onPreviewArtifact?.({
          path: `jsx:${lang}:${hashCode(code)}`,
          filename,
          inline: { kind: lang, code },
        });
      }}
    >
      <ReactIcon />
      <span>React preview</span>
    </button>
  );
}

function ReactIcon() {
  return (
    <svg width={13} height={13} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true">
      <circle cx="12" cy="12" r="1.6" fill="currentColor" stroke="none" />
      <ellipse cx="12" cy="12" rx="10" ry="4" />
      <ellipse cx="12" cy="12" rx="10" ry="4" transform="rotate(60 12 12)" />
      <ellipse cx="12" cy="12" rx="10" ry="4" transform="rotate(120 12 12)" />
    </svg>
  );
}

/** Renders a markdown string with syntax-highlighted code fences, mermaid
 *  diagrams and glass-styled links — the assistant's normal answer body. */
function Markdown({
  content,
  onPreviewArtifact,
}: {
  content: string;
  onPreviewArtifact?: (artifact: ChatArtifact) => void;
}) {
  const inlineCodeStyle = useInlineCodeStyle();
  return (
    <div className="chat-markdown">
      <ReactMarkdown
        remarkPlugins={[remarkGfm, remarkMath]}
        rehypePlugins={[rehypeKatex]}
        components={{
          code({ className, children, ...props }) {
            const match = /language-(\w+)/.exec(className || "");
            const codeString = String(children).replace(/\n$/, "");

            // Inline code: no language class and short.
            if (!match && !String(children).includes("\n")) {
              return (
                <code style={inlineCodeStyle} {...props}>
                  {children}
                </code>
              );
            }

            // Mermaid diagrams render as inline SVG, not as highlighted text.
            if (match && match[1] === "mermaid") {
              return <MermaidDiagram code={codeString} />;
            }

            // React/JSX artifacts open as a live preview in the side pane
            // (rendered by ArtifactPreviewPane), not inline in the chat.
            if (match && (match[1] === "jsx" || match[1] === "tsx")) {
              return (
                <JsxArtifactChip
                  code={codeString}
                  lang={match[1] as "jsx" | "tsx"}
                  onPreviewArtifact={onPreviewArtifact}
                />
              );
            }

            // Code block with language.
            return (
              <div className="chat-code-block">
                <div className="chat-code-header">
                  <span className="chat-code-lang">{match ? match[1] : "text"}</span>
                  <CopyButton code={codeString} />
                </div>
                <SyntaxHighlighter
                  style={{}}
                  language={match ? match[1] : "text"}
                  PreTag="div"
                  customStyle={{
                    margin: 0,
                    background: "transparent",
                    padding: "12px 16px",
                    fontSize: "12px",
                    fontFamily: "var(--font-mono)",
                    lineHeight: 1.5,
                    overflowX: "auto",
                  }}
                  codeTagProps={{ style: { fontFamily: "var(--font-mono)" } }}
                >
                  {codeString}
                </SyntaxHighlighter>
              </div>
            );
          },
          // Render links with target=_blank and glass-appropriate styling.
          a({ href, children }) {
            return (
              <a
                href={href}
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: "var(--accent)" }}
              >
                {children}
              </a>
            );
          },
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
}

/** One step inside an activity group. Tool steps carry the call's `ToolData`;
 *  think steps (`think` set, `data` null) are reasoning interludes folded into
 *  the SAME group so a turn renders as one outer container instead of
 *  alternating activity/thinking blocks. `before`/`after` carry narration
 *  text the model produced around the call — folded into the step instead of
 *  floating as standalone text nodes between rows (the source of the old flat
 *  layout's noise). */
interface ActivityStep {
  data: ToolData | null;
  done: boolean;
  before?: string;
  after?: string;
  /** Reasoning text when this step is a thinking interlude. */
  think?: string;
}

/** A grouped run of tool steps, collapsed into one summary line by default. */
interface ActivityGroup {
  steps: ActivityStep[];
}

/** A render block: either a standalone text/think segment (rendered as
 *  before) or a collapsed activity group spanning a contiguous tool run. */
type Block =
  | { kind: "text"; text: string }
  | { kind: "think"; text: string; done: boolean }
  | { kind: "activity"; group: ActivityGroup };

/** Walk the parsed segments and collapse ALL of a turn's tool activity into a
 *  single ActivityGroup block — including any `<think>` reasoning interludes,
 *  which become think steps inside the group rather than breaking it (the old
 *  break-at-think rule produced one top-level activity block + one "Thought
 *  process" block per tool call, scrolling forever on multi-step tasks).
 *
 *  Boundary rules:
 *  - Text before the first tool/think renders ABOVE the container as markdown.
 *  - A group starts at the first `tool` or `think` segment and absorbs every
 *    following `tool`/`think`/`text` segment to the end of the message —
 *    at most ONE activity block per turn.
 *  - Mid-run text is narration: it folds into the next step's `before`.
 *  - Text trailing the last tool/think is the model's synthesized answer and
 *    renders OUTSIDE the group as markdown, after the summary.
 *  - A turn with thinking but NO tool calls keeps the old behavior: the think
 *    segment stays its own standalone disclosure. */
function groupSegments(segments: Segment[]): Block[] {
  // No tool activity at all → pass through (a lone thinking block stays its
  // own disclosure, text renders as markdown).
  if (!segments.some((s) => s.type === "tool")) {
    return segments.map((seg) =>
      seg.type === "think"
        ? { kind: "think", text: seg.text, done: seg.done }
        : { kind: "text", text: seg.type === "text" ? seg.text : "" },
    );
  }

  const blocks: Block[] = [];
  const steps: ActivityStep[] = [];
  let pendingText: string | null = null; // narration held for the next step
  let started = false;

  for (const seg of segments) {
    if (seg.type === "text" && !started) {
      // Leading text before any activity: renders above the container.
      blocks.push({ kind: "text", text: seg.text });
      continue;
    }
    if (seg.type === "tool") {
      started = true;
      steps.push({
        data: seg.data,
        done: seg.done,
        before: pendingText ?? undefined,
      });
      pendingText = null;
      continue;
    }
    if (seg.type === "think") {
      started = true;
      // Skip empty think shells (e.g. an opening tag that just started
      // streaming); any pending narration stays held for the next step.
      if (seg.text.length > 0) {
        steps.push({
          data: null,
          done: seg.done,
          think: seg.text,
          before: pendingText ?? undefined,
        });
        pendingText = null;
      }
      continue;
    }
    // text while active: narration between calls — hold until the next step
    // claims it as `before`, or it becomes the trailing answer.
    pendingText = (pendingText ?? "") + seg.text;
  }

  if (steps.length > 0) {
    blocks.push({ kind: "activity", group: { steps } });
  }
  if (pendingText != null && pendingText.trim().length > 0) {
    blocks.push({ kind: "text", text: pendingText });
  }
  return blocks;
}

export function MessageBubble({
  message,
  live,
  onEdit,
  onRepeat,
  artifacts,
  onPreviewArtifact,
}: Props) {
  const isUser = message.role === "user";

  // A persisted compaction-summary row renders as a low-weight "earlier context
  // compacted" marker (not a real bubble) so the user understands why
  // scrolling back shows condensed rather than verbatim detail. Tapping
  // reveals the actual summary text that replaced the original turns.
  // Sentinel must match the `COMPACTED_PREFIX` constant in
  // src-tauri/src/chat/compaction.rs.
  const COMPACTED_PREFIX = "[compacted context]";
  if (message.role === "system" && message.content.trimStart().startsWith(COMPACTED_PREFIX)) {
    const summary = message.content.trimStart().slice(COMPACTED_PREFIX.length).replace(/^[\s:\n]+/, "");
    return <CompactedContextMarker summary={summary} />;
  }
  // Parse attachment markers (e.g. "[Attached image: x]") out of the content
  // so they render as visual cards above the text instead of inline strings.
  // Live attachments (optimistic message) carry image base64 for thumbnails.
  const { attachments: msgAttachments, text: cleanContent } = parseAttachments(
    message.content,
    message.attachments,
  );
  // User messages are rendered verbatim; assistant messages are split into
  // reasoning / tool-call / answer segments (Claude-style process view).
  const segments: Segment[] = isUser
    ? [{ type: "text", text: cleanContent }]
    : parseSegments(cleanContent);

  // Copy action yields the visible answer text only (no process markup).
  const plainText = segments
    .filter((s): s is Extract<Segment, { type: "text" }> => s.type === "text")
    .map((s) => s.text)
    .join("")
    .trim();

  // Fold the turn's entire tool activity (including thinking interludes and
  // mid-run narration) into ONE ActivitySummary container. A trailing
  // plain-text answer renders as normal markdown OUTSIDE the group — the core
  // fix for the noisy per-call rows + interleaved-blocks layout.
  const blocks = isUser ? null : groupSegments(segments);

  return (
    <div className={`chat-bubble${isUser ? " user" : " assistant"}`}>
      {msgAttachments.length > 0 && <MessageAttachments attachments={msgAttachments} />}
      <div className="chat-bubble-inner">
        {isUser
          ? cleanContent.trim().length > 0 && (
              <Markdown content={cleanContent} onPreviewArtifact={onPreviewArtifact} />
            )
          : blocks!.map((b, i) =>
              b.kind === "activity" ? (
                <ActivitySummary key={i} group={b.group} />
              ) : b.kind === "think" ? (
                b.text.length > 0 ? (
                  <ThinkingBlock key={i} thinking={b.text} done={b.done} />
                ) : null
              ) : b.text.trim().length > 0 ? (
                <Markdown key={i} content={b.text} onPreviewArtifact={onPreviewArtifact} />
              ) : null,
            )}
        {!isUser && artifacts && artifacts.length > 0 && (
          <MessageArtifacts artifacts={artifacts} onPreviewArtifact={onPreviewArtifact} />
        )}
      </div>
      {!live && (
        <MessageActions content={plainText || message.content} onEdit={onEdit} onRepeat={onRepeat} />
      )}
    </div>
  );
}