// A single chat message bubble. User messages right-aligned, assistant
// left-aligned. Renders markdown via react-markdown with syntax highlighting.
// Streaming token-by-token updates are debounced to ~50ms by the caller —
// this component simply accepts a `content: string` prop and renders it.
//
// BUNDLE: react-syntax-highlighter + its Prism/refractor language pack (~700
// KB raw / ~230 KB gzip) is the single biggest dep in the main chunk. It's
// only needed once a code block or tool step actually renders, NOT on the
// empty welcome screen — so we lazy-load it via dynamic import() in
// StepCodeHighlighter below. That moves it out of the initial bundle.
import { Fragment, lazy, memo, Suspense, useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
// NOTE: katex.min.css is imported at app entry (src/main.tsx) so this file
// does NOT re-import it — see PERFORMANCE_AUDIT.md C8. Doing it twice would
// ship two copies in the lazy MessageBubble chunk.
import type { ChatMessage, ChatPerfPayload } from "../../lib/ipc";
import { readArtifactPreview } from "../../lib/ipc";
import type { ChatArtifact } from "../../state/chat";
import { useChatStore } from "../../state/chat";
import { useUiStore } from "../../state/ui";
import { parseUnifiedDiff } from "../../lib/diff";
import { openInBrowserPane } from "../../lib/openBrowserPane";
import { DiffCard, type EditPayload } from "./DiffCard";
import { sameTurnFile, TurnChangesRow } from "./TurnChangesRow";
// InlineDiagram (vector diagrams) and MermaidDiagram (mermaid + its
// highlight.js language pack) are rarely seen on the initial chat surface and
// pull in heavy dependencies; lazy-load both so the main bundle stays small.
// The mermaid bundle in particular drags ~1.4 MB of diagram + language-
// definition code that the empty welcome screen never touches. DiffCard stays
// eager: it's a tiny component (no heavy deps) and the per-edit review card
// must render synchronously with the rest of the message.
const InlineDiagram = lazy(() => import("./InlineDiagram").then((m) => ({ default: m.InlineDiagram })));
const MermaidDiagram = lazy(() => import("./MermaidDiagram").then((m) => ({ default: m.MermaidDiagram })));
import { MessageAttachments, parseAttachments } from "./MessageAttachments";
import { useSyntaxTheme } from "../../hooks/useSyntaxTheme";
import type { SyntaxHighlighterProps, SyntaxStyle } from "../../lib/syntaxHighlighter";
import { loadSyntaxHighlighter } from "../../lib/syntaxHighlighter";

type SyntaxHighlighterComponent = (props: SyntaxHighlighterProps) => React.ReactNode;

/** Hook that loads a lazy component once (on mount) and resolves it via the
 *  provided async loader. The component stays null until the dynamic import
 *  finishes, then re-renders with the loaded module. Safe across StrictMode
 *  double-invoke (the loader memoizes internally). */
function useLazyComponent<T>(
  loader: () => Promise<T>,
  onReady: (value: T) => void,
) {
  useEffect(() => {
    let mounted = true;
    void loader().then((mod) => {
      if (mounted) onReady(mod);
    });
    return () => {
      mounted = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
}

interface Props {
  message: ChatMessage;
  /** True for the in-progress streaming bubble — hides the action bar. */
  live?: boolean;
  /** When provided (user messages), shows an "Edit" action that opens an inline
   *  editor; calling it submits the edited content (edit-to-fork). */
  onEdit?: (newContent: string) => void;
  /** When provided (assistant messages), shows a "Regenerate" action. */
  onRepeat?: () => void;
  /** When provided, shows a "Delete" action that removes this message from
   *  the chat (both locally and on the backend). Available on every non-
   *  live, non-system bubble (user and assistant alike). */
  onDelete?: () => void;
  /** Applies the "previous version" className to a row in a retired branch
   *  (roadmap #9). True when `message.supersededBy` is set. */
  superseded?: boolean;
  /** True when this row begins a new retired segment (the first superseded row
   *  after an active one) — renders the "— edited —" divider above it. */
  segmentStart?: boolean;
  /** Artifacts generated by this message, shown as clickable chips below it. */
  artifacts?: ChatArtifact[];
  /** Open an artifact in the preview pane (used by the inline chips). */
  onPreviewArtifact?: (artifact: ChatArtifact) => void;
  /** Numeric message id, emitted as `data-msg-id` on the root bubble so the
   *  TurnNavigator can scroll to it. Omitted on the live streaming bubble. */
  msgId?: number;
  /** Live perf snapshot (elapsedMs, etc.) from `chat:perf` for the streaming
   *  bubble — used to show "Working for Xs" while the turn is in flight. */
  livePerf?: ChatPerfPayload | null;
}

// --- Inline SVG icons (Claude-style, stroke-based, currentColor). ---
const iconProps = {
  width: 15,
  height: 15,
  viewBox: "0 0 24 24",
  fill: "none",
  stroke: "currentColor",
  strokeWidth: 2,
  strokeLinecap: "round" as const,
  strokeLinejoin: "round" as const,
};

function CopyIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <rect x="9" y="9" width="13" height="13" rx="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

function CheckIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <path d="M20 6 9 17l-5-5" />
    </svg>
  );
}

function EditIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <path d="M12 20h9" />
      <path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4Z" />
    </svg>
  );
}

function RepeatIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <path d="M3 2v6h6" />
      <path d="M3 13a9 9 0 1 0 3-7.7L3 8" />
    </svg>
  );
}

function TrashIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <path d="M3 6h18" />
      <path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
      <path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6" />
      <path d="M10 11v6" />
      <path d="M14 11v6" />
    </svg>
  );
}

function FileIcon() {
  return (
    <svg
      width={13}
      height={13}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>
  );
}

/** Download/preview chip for a generated file. */
function ArtifactChip({
  artifact,
  onPreviewArtifact,
}: {
  artifact: ChatArtifact;
  onPreviewArtifact?: (artifact: ChatArtifact) => void;
}) {
  return (
    <button
      type="button"
      className="chat-artifact-chip"
      title={`Preview ${artifact.filename}`}
      onClick={(e) => {
        e.currentTarget.blur();
        onPreviewArtifact?.(artifact);
      }}
    >
      <FileIcon />
      <span>{artifact.filename}</span>
    </button>
  );
}

/** The files an assistant message produced. .html/.svg artifacts are probed via
 *  InlineDiagram, which renders ONLY true diagrams (kind "diagram", authored by
 *  generate_diagram) inline; a plain .html webpage or .svg image falls back to
 *  a download chip so it opens in the preview pane instead. Every other file is
 *  always a download chip. */
function MessageArtifacts({
  artifacts,
  onPreviewArtifact,
}: {
  artifacts: ChatArtifact[];
  onPreviewArtifact?: (artifact: ChatArtifact) => void;
}) {
  const isVisual = (name: string) => {
    const ext = name.split(".").pop()?.toLowerCase();
    return ext === "html" || ext === "svg";
  };
  const chips = artifacts.filter((a) => !isVisual(a.filename));
  const visuals = artifacts.filter((a) => isVisual(a.filename));
  return (
    <>
      {visuals.map((a) => (
        <Suspense key={a.path} fallback={
          <div className="chat-msg-artifacts">
            <ArtifactChip artifact={a} onPreviewArtifact={onPreviewArtifact} />
          </div>
        }>
          <InlineDiagram
            artifact={a}
            onFallback={() => (
              <div className="chat-msg-artifacts">
                <ArtifactChip artifact={a} onPreviewArtifact={onPreviewArtifact} />
              </div>
            )}
          />
        </Suspense>
      ))}
      {chips.length > 0 && (
        <div className="chat-msg-artifacts" aria-label="Generated files">
          {chips.map((a) => (
            <ArtifactChip key={a.path} artifact={a} onPreviewArtifact={onPreviewArtifact} />
          ))}
        </div>
      )}
    </>
  );
}

/** Per-message action bar (Claude-style icons): copy for every message, edit
 *  for user messages, regenerate for assistant messages, delete for any
 *  persisted message. Appears on hover under the bubble. */
function MessageActions({
  content,
  onEdit,
  onRepeat,
  onDelete,
}: {
  content: string;
  onEdit?: (content: string) => void;
  onRepeat?: () => void;
  onDelete?: () => void;
}) {
  const [copied, setCopied] = useState(false);
  const copy = useCallback(
    async (e: React.MouseEvent<HTMLButtonElement>) => {
      // Drop focus so the hover-only action bar doesn't stay pinned open
      // after a mouse click.
      e.currentTarget.blur();
      try {
        await navigator.clipboard.writeText(content);
        setCopied(true);
        setTimeout(() => setCopied(false), 1800);
      } catch {
        // Clipboard unavailable — silently ignore.
      }
    },
    [content],
  );

  return (
    <div className="chat-msg-actions">
      <button
        className="chat-msg-action"
        onClick={copy}
        title={copied ? "Copied" : "Copy message"}
        aria-label="Copy message"
      >
        {copied ? <CheckIcon /> : <CopyIcon />}
      </button>
      {onRepeat && (
        <button
          className="chat-msg-action"
          onClick={(e) => {
            e.currentTarget.blur();
            onRepeat();
          }}
          title="Regenerate response"
          aria-label="Regenerate response"
        >
          <RepeatIcon />
        </button>
      )}
      {onEdit && (
        <button
          className="chat-msg-action"
          onClick={(e) => {
            e.currentTarget.blur();
            onEdit(content);
          }}
          title="Edit message"
          aria-label="Edit message"
        >
          <EditIcon />
        </button>
      )}
      {onDelete && (
        <button
          className="chat-msg-action chat-msg-action-danger"
          onClick={(e) => {
            // Drop focus so the hover-only action bar doesn't stay pinned
            // open after the click.
            e.currentTarget.blur();
            onDelete();
          }}
          title="Delete message"
          aria-label="Delete message"
        >
          <TrashIcon />
        </button>
      )}
    </div>
  );
}

/** Codex-style pre-token indicator: a single quiet monospace pulse — no
 *  bouncing dots, just a subtle "working…" line that recedes visually. */
// TypingIndicator moved to ./TypingIndicator (PERF item 12) — re-exported
// here so existing imports keep working without dragging react-markdown into
// the entry chunk via ChatView.
export { TypingIndicator } from "./TypingIndicator";

/** Low-weight, tappable marker shown in the timeline where older context was
 *  condensed by the local-model compaction framework. Expands to reveal the
 *  actual summary that replaced the original turns. Reuses the muted aesthetic
 *  of `.chat-status-notice` / `.chat-activity-done`. */
function CompactedContextMarker({ summary }: { summary: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="chat-compacted-marker">
      <button
        type="button"
        className="chat-compacted-toggle"
        aria-expanded={open}
        onClick={() => setOpen((v) => !v)}
      >
        <span className="chat-compacted-dash" aria-hidden="true">—</span>
        earlier context compacted
        <span className={`chat-thinking-chevron${open ? " open" : ""}`}>›</span>
      </button>
      {open && summary && (
        <div className="chat-compacted-summary">{summary}</div>
      )}
    </div>
  );
}

/** A tool-call process step emitted by the backend as `<tool>{json}</tool>`. */
interface ToolData {
  kind?: string;
  title?: string;
  detail?: string;
  lang?: string;
  code?: string;
  /** File-edit payloads (write_file / edit_file) carry the target path and
   *  the old/new content so the UI can render an inline diff review card
   *  (mockup 01 callout 5). See `tool_block` in src-tauri/src/chat/proto.rs. */
  path?: string;
  edit?: EditPayload;
  /** Subagent Task steps carry the spawned agent's role + task so the row
   *  renders as the "SubAgent <role> · <task>" chip (shine while running). */
  role?: string;
  task?: string;
  /** Optional result text rendered once the call completes. The backend
   *  doesn't populate this today (tool output is summarized by the model in
   *  the following narration), but the expandable step detail shows args/code
   *  regardless — `result` is reserved so a future backend field flows
   *  straight into the same disclosure. */
  result?: string;
}

type Segment =
  | { type: "text"; text: string }
  | { type: "think"; text: string; done: boolean }
  | { type: "tool"; data: ToolData | null; done: boolean };

/** Split an assistant message into ordered segments: plain markdown text,
 *  `<think>` reasoning blocks, and `<tool>` process cards. A block whose
 *  closing tag hasn't streamed in yet is marked `done: false`. */
function parseSegments(content: string): Segment[] {
  const segs: Segment[] = [];
  let rest = content;
  const tagRe = /<(think|tool)>/;
  for (;;) {
    const m = tagRe.exec(rest);
    if (!m) {
      if (rest) segs.push({ type: "text", text: rest });
      break;
    }
    const before = rest.slice(0, m.index);
    if (before) segs.push({ type: "text", text: before });

    const tag = m[1];
    const afterOpen = rest.slice(m.index + m[0].length);
    const close = `</${tag}>`;
    const ci = afterOpen.indexOf(close);
    const inner = ci === -1 ? afterOpen : afterOpen.slice(0, ci);
    const done = ci !== -1;

    if (tag === "think") {
      segs.push({ type: "think", text: inner.trim(), done });
    } else {
      let data: ToolData | null = null;
      try {
        data = JSON.parse(inner) as ToolData;
      } catch {
        data = null;
      }
      segs.push({ type: "tool", data, done });
    }

    if (ci === -1) break;
    rest = afterOpen.slice(ci + close.length);
  }
  return segs;
}

function ThinkingBlock({ thinking, done }: { thinking: string; done: boolean }) {
  // Expanded while streaming (live), collapsed once the turn finishes.
  const [open, setOpen] = useState(!done);
  // Auto-collapse when the turn completes — but only if the user hasn't
  // manually toggled it.
  const [userToggled, setUserToggled] = useState(false);
  useEffect(() => {
    if (done && !userToggled) setOpen(false);
  }, [done, userToggled]);

  const toggle = () => {
    setUserToggled(true);
    setOpen((o) => !o);
  };

  return (
    <div className={`chat-thinking${done ? "" : " live"}`}>
      <button
        className="chat-thinking-toggle"
        onClick={toggle}
        title={open ? "Hide thinking" : "Show thinking"}
      >
        <span className={`chat-thinking-icon${open ? " open" : ""}`}>›</span>
        {done ? "Thinking" : "Thinking…"}
      </button>
      {open && (
        <div className="chat-thinking-body">
          {thinking}
        </div>
      )}
    </div>
  );
}

function SearchIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function GlobeIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <circle cx="12" cy="12" r="10" />
      <path d="M2 12h20" />
      <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
    </svg>
  );
}

function TerminalIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <polyline points="4 17 10 11 4 5" />
      <line x1="12" y1="19" x2="20" y2="19" />
    </svg>
  );
}

function WrenchIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z" />
    </svg>
  );
}

/** Per-tool-kind icon for an activity step (Cursor-style: recognizable glyph
 *  per action instead of one uniform dot). */
function ToolIcon({ kind }: { kind?: string }) {
  switch (kind) {
    case "search":
      return <SearchIcon />;
    case "web":
    case "browser":
      return <GlobeIcon />;
    case "file":
      return <FileIcon />;
    case "code":
      return <TerminalIcon />;
    default:
      return <WrenchIcon />;
  }
}

/** Step status: spinner while the call runs, green check once it completes —
 *  the at-a-glance progress signal Cursor gives every tool row. */
function StepStatusIcon({ done }: { done: boolean }) {
  if (!done) return <span className="chat-activity-spinner" aria-label="running" />;
  return (
    <span className="chat-step-done-icon" aria-label="done">
      <CheckIcon />
    </span>
  );
}

/** A short, *specific* label for one tool step — rendered in monospace like a
 *  terminal log entry. The backend emits a generic `title` ("Reading a web page",
 *  "Searching the web") but also a `detail` carrying the actual target (url /
 *  query / filename). We prefer the detail so each step reads as what it
 *  actually touched, falling back to the title only when no detail is available.
 *  Format: `command  target` (two-space separation, log-style). */
function stepLabel(data: ToolData | null): string {
  if (!data) return "working…";
  const title = data.title?.trim() || "working…";
  const detail = data.detail?.trim();
  // Shell commands read terminal-style, like Cursor's command rows.
  if (data.kind === "code" && data.code) {
    const cmd = data.code.trim();
    return `$ ${cmd.length > 90 ? `${cmd.slice(0, 90)}…` : cmd}`;
  }
  if (!detail) return title;
  // For code-producing tools the "detail" is sometimes the full code body —
  // too long for a row label; in that case keep the title.
  if (data.code && detail.length > 80) return title;
  // Log-style: "write_file  src/main.rs" rather than "Writing file — src/main.rs"
  const cmd = title.toLowerCase().replace(/\s+/g, "_").replace(/ing$/, "");
  return `${cmd}  ${detail}`;
}


/** Detect whether a string looks like a unified diff. */
function looksLikeDiff(text: string): boolean {
  return text.startsWith("diff --git") || text.startsWith("--- ") || text.includes("\n@@ ");
}

/** Render a unified diff inline inside a tool step body. Reuses the existing
 *  diff parser and CSS classes for a terminal-native look. */
function InlineDiff({ diffText }: { diffText: string }) {
  const files = useMemo(() => parseUnifiedDiff(diffText), [diffText]);
  if (files.length === 0) return <div className="chat-step-detail">{diffText}</div>;
  return (
    <div className="chat-diff-inline">
      {files.map((file, i) => (
        <div className="diff-file" key={`${file.newPath || file.oldPath || i}-${i}`}>
          <div className="diff-file-header">
            {file.oldPath === file.newPath || file.newPath === ""
              ? file.oldPath || file.newPath || `file ${i + 1}`
              : `${file.oldPath} → ${file.newPath}`}
          </div>
          {file.lines
            .filter((l) => l.type !== "meta")
            .map((line, j) => (
              <div key={j} className={`diff-line ${line.type}`}>
                {line.type === "add" ? "+ " : line.type === "del" ? "- " : line.type === "hunk" ? "" : "  "}
                {line.text}
              </div>
            ))}
        </div>
      ))}
    </div>
  );
}

/** A single tool-call row inside an expanded ProcessSummary. Renders the
 *  step's type icon + a specific label (the actual URL/query/filename, not a
 *  repeated generic title). Any narration text the model produced around
 *  this step is folded into the row above/below the label. The whole row is
 *  itself expandable (a second, nested disclosure) to reveal full detail:
 *  exact tool kind, detail string, and the code block for code-producing
 *  tools. File edits that contain a unified diff render as an inline diff. */
/** Syntax highlighter component for tool-step and markdown code blocks.
 *  Uses the current theme's CSS custom properties (--syntax-*) for token
 *  colors, switching instantly when data-theme changes.
 *
 *  BUNDLE: the Prism highlighter + language pack is ~700 KB and only needed
 *  once a code block renders — so we load it via dynamic import() on first
 *  use. Before then we render the raw code in a <pre> (styled the same) so
 *  the user sees content immediately; it upgrades to highlighted once the
 *  chunk lands. */
function StepCodeHighlighter({ code, language }: { code: string; language: string }) {
  const theme = useSyntaxTheme();
  // `comp` resolves to the lazy-loaded Prism component after first use.
  const [comp, setComp] = useState<SyntaxHighlighterComponent | null>(null);
  // The loaded value IS a function component — pass it via an updater fn,
  // otherwise React treats it as a setState updater and calls it with the
  // previous state (null) as props, crashing inside the highlighter.
  useLazyComponent(loadSyntaxHighlighter, (c) => setComp(() => c));
  if (!comp) {
    // Fallback <pre> before the chunk loads — styled to match the highlighter's
    // output so there's no layout shift when it upgrades.
    return (
      <pre
        className="code-block-pre-fallback"
        style={{
          margin: 0,
          background: "transparent",
          padding: "12px 16px",
          fontSize: "12px",
          fontFamily: "var(--font-mono)",
          lineHeight: 1.5,
          overflowX: "auto",
        }}
      >
        <code>{code}</code>
      </pre>
    );
  }
  const SyntaxHighlighter = comp;
  return (
    <SyntaxHighlighter
      style={theme}
      language={language}
      PreTag="div"
      customStyle={{
        margin: 0,
        background: "transparent",
        padding: "12px 16px",
        fontSize: "12px",
        fontFamily: "var(--font-mono)",
        lineHeight: 1.5,
        overflowX: "auto",
      }}
      codeTagProps={{ style: { fontFamily: "var(--font-mono)" } }}
    >
      {code}
    </SyntaxHighlighter>
  );
}

function ActivityStepRow({
  step,
  done,
}: {
  step: ActivityStep;
  done: boolean;
}) {
  const [open, setOpen] = useState(false);
  const hasBody = Boolean(
    step.data?.code || step.data?.detail || step.data?.result,
  );
  // Subagent Task steps render as the agent chip — same visual language as
  // the git sidebar's AGENTS rows: icon + SubAgent + blue role + task, a
  // shimmer sweep while the agent runs, click opens the Agents pane.
  if (step.data?.kind === "subagent") {
    const role = step.data.role || "agent";
    const task = step.data.task || step.data.detail || "";
    const openAgent = () => {
      const s = useChatStore.getState();
      const list = s.activeChatSessionId
        ? Object.values(s.subagents[s.activeChatSessionId] ?? {})
        : [];
      const match =
        list.find((x) => x.status === "running" && x.task === task) ??
        list.find((x) => x.task === task) ??
        list.find((x) => x.role === role && x.status === "running");
      if (match) {
        useUiStore.getState().setActiveSubagentId(match.id);
        useUiStore.getState().addTab("agents");
      }
    };
    return (
      <div className={`chat-agent-chip${done ? "" : " running"}`}>
        <button
          type="button"
          className="chat-agent-chip-btn"
          onClick={openAgent}
          title={`${task} — click to watch this agent`}
        >
          <svg className="chat-agent-chip-icon" width={13} height={13} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} strokeLinecap="round" strokeLinejoin="round">
            <rect x="4" y="8" width="16" height="12" rx="2" />
            <circle cx="9" cy="14" r="1.2" fill="currentColor" stroke="none" />
            <circle cx="15" cy="14" r="1.2" fill="currentColor" stroke="none" />
            <path d="M12 8V4M8 4h8" />
          </svg>
          <span className="chat-agent-chip-label">SubAgent</span>
          <span className="chat-agent-chip-role">{role}</span>
          <span className="chat-agent-chip-sep" aria-hidden="true">·</span>
          <span className="chat-agent-chip-task">{task}</span>
          {done ? (
            <span className="chat-agent-chip-check" aria-hidden="true">✓</span>
          ) : null}
        </button>
      </div>
    );
  }
  return (
    <div className={`chat-step${done ? "" : " live"}`}>
      <button
        className="chat-step-toggle"
        onClick={() => hasBody && setOpen((o) => !o)}
        title={hasBody ? (open ? "Hide details" : "Show details") : undefined}
        disabled={!hasBody}
      >
        <span className="chat-step-status">
          <StepStatusIcon done={done} />
        </span>
        <span className="chat-step-icon">
          <ToolIcon kind={step.data?.kind} />
        </span>
        <span className="chat-step-label">{stepLabel(step.data)}</span>
        {hasBody && (
          <span className={`chat-thinking-chevron${open ? " open" : ""}`}>›</span>
        )}
      </button>
      {open && hasBody && (
        <div className="chat-step-body">
          {step.data?.detail && (
            <div className="chat-step-detail">{step.data.detail}</div>
          )}
          {step.data?.code && (
            looksLikeDiff(step.data.code) ? (
              <InlineDiff diffText={step.data.code} />
            ) : (
              <div className="chat-code-block">
                <div className="chat-code-header">
                  <span className="chat-code-lang">{step.data.lang || "text"}</span>
                  <CopyButton code={step.data.code} />
                </div>
                <StepCodeHighlighter code={step.data.code} language={step.data.lang || "text"} />
              </div>
            )
          )}
          {step.data?.result && (
            looksLikeDiff(step.data.result) ? (
              <InlineDiff diffText={step.data.result} />
            ) : (
              <div className="chat-step-result">{step.data.result}</div>
            )
          )}
        </div>
      )}
    </div>
  );
}

/** The single collapsed row that wraps an assistant turn's ENTIRE process —
 *  thinking, tool calls, and file edits — into one line ("Worked for Xs" once
 *  done; a live action label while streaming). Expanding reveals what the turn
 *  actually did, in source order: ThinkingBlock disclosures, ActivityStepRow
 *  tool rows, and inline DiffCards. The model's synthesized answer and the
 *  files-changed summary render OUTSIDE this row, after it.
 *
 *  The label is computed by the caller (MessageBubbleInner) so this component
 *  stays presentational: `live` drives the spinner/check icon and `label` is
 *  either the live action, "Worked for Xs" (when a duration is known), or a
 *  legacy one-line summary fallback. */
function ProcessSummary({
  live,
  label,
  children,
}: {
  live: boolean;
  label: string;
  children: ReactNode;
}) {
  // The toggle IS the assistant-message-header slot: plain "Working for Xs"
  // while streaming, "Worked for Xs ›" once done — same muted header style,
  // with the chevron marking it expandable.
  //
  // Auto-expand while the TURN is in flight (so live tool activity and
  // thinking are visible — they already show what's happening, so no separate
  // action line is needed), auto-collapse when it ends. The turn-level live
  // flag doesn't flicker between tool rounds (unlike per-step state), so
  // this doesn't flash. A manual toggle latches for the rest of the turn.
  const [open, setOpen] = useState(live);
  const [userToggled, setUserToggled] = useState(false);
  useEffect(() => {
    if (!userToggled) setOpen(live);
  }, [live, userToggled]);

  return (
    <div className={`chat-process${live ? " live" : ""}`}>
      <button
        type="button"
        className="chat-process-toggle"
        onClick={() => {
          setUserToggled(true);
          setOpen((o) => !o);
        }}
        title={open ? "Hide what was done" : "Show what was done"}
        aria-expanded={open}
      >
        <span className="chat-process-label">{label}</span>
        <span className={`chat-thinking-chevron${open ? " open" : ""}`} aria-hidden="true">
          ›
        </span>
      </button>
      {open && <div className="chat-process-body">{children}</div>}
    </div>
  );
}

/** One render block of an assistant turn's process region. `activity` flattens
 *  to its step rows (the outer ProcessSummary is the single collapse; nested
 *  collapsibles would be confusing). `diff` keeps its inline DiffCard. `think`
 *  is its own disclosure. `text` is mid-run narration as markdown. */
/** Render one process block inside the ProcessSummary region. Keys carry the
 *  block KIND plus the loop index (PERFORMANCE_AUDIT.md F6): a bare `key={i}`
 *  remounts a block whenever the block at that index changes kind (e.g. a
 *  think block that gains a tool run below it mid-stream), losing collapse
 *  state. Diff blocks key on their file path, which is unique per turn. */
function renderProcessBlock(
  b: Block,
  i: number,
  onPreviewArtifact?: (artifact: ChatArtifact) => void,
) {
  switch (b.kind) {
    case "activity":
      return (
        <div className="chat-activity-steps" key={`activity:${i}`}>
          {b.group.steps.map((step, j) => (
            <ActivityStepRow
              key={`${step.data?.kind ?? "step"}:${step.data?.path ?? step.data?.title ?? j}:${j}`}
              step={step}
              done={step.done}
            />
          ))}
        </div>
      );
    case "diff":
      return (
        <Fragment key={`diff:${b.step.data?.path ?? i}`}>
          <DiffCard path={b.step.data!.path!} edit={b.step.data!.edit!} done={b.step.done} />
        </Fragment>
      );
    case "think":
      return b.text.length > 0 ? (
        <ThinkingBlock key={`think:${i}`} thinking={b.text} done={b.done} />
      ) : null;
    case "text":
      return b.text.trim().length > 0 ? (
        <Markdown key={`text:${i}`} content={b.text} onPreviewArtifact={onPreviewArtifact} />
      ) : null;
  }
}

/** Format a worked-duration (seconds) as "1s", "8s", or "2m 13s". */
function formatDuration(sec: number): string {
  if (sec < 1) return "1s";
  if (sec < 60) return `${sec}s`;
  const m = Math.floor(sec / 60);
  const s = sec % 60;
  return s ? `${m}m ${s}s` : `${m}m`;
}

/** Live whole-seconds elapsed for the "Working for Xs" header. Reading the
 *  latest `chat:perf` snapshot directly made the timer feel sluggish: the
 *  backend heartbeat emits every ~500ms through a throttle shared with
 *  token-driven emits (so gaps can stretch toward ~1s), then the value crosses
 *  IPC + render latency and gets floored to whole seconds — the visible counter
 *  could lag wall-clock by over a second and tick unevenly. Instead, each
 *  snapshot ANCHORS true elapsed at its arrival instant and a local 250ms
 *  ticker interpolates between anchors, so the displayed second flips on real
 *  time boundaries no matter when events land.
 *
 *  `fallback` (the bubble's live flag) keeps the ticker running from MOUNT
 *  when no perf snapshots exist at all — harness turns (claude/opencode CLIs)
 *  never emit chat:perf, so without the fallback their header stuck on a bare
 *  "Working" with no seconds. */
function useLiveElapsedSec(
  perf: ChatPerfPayload | null | undefined,
  fallback: boolean,
): number | null {
  const [sec, setSec] = useState<number | null>(null);
  const anchor = useRef<{ baseMs: number; at: number } | null>(null);
  const mountedAt = useRef<number>(performance.now());
  // Re-anchor ONLY when a new snapshot object lands — not on unrelated
  // re-renders (token flushes), which would otherwise keep advancing `at`
  // against a stale baseMs and freeze the interpolation mid-stream.
  const lastPerf = useRef<ChatPerfPayload | null | undefined>(undefined);
  if (perf !== lastPerf.current) {
    lastPerf.current = perf;
    anchor.current = perf ? { baseMs: perf.elapsedMs, at: performance.now() } : null;
  }

  // Adopt each snapshot's truth as it lands. TURN RESET: within one turn
  // elapsedMs only grows, so a snapshot landing FAR behind the previous
  // snapshot's means a NEW turn is reusing this bubble (cancel + resend
  // before the live row remounts) — adopt the smaller truth instead of
  // letting the monotonic display guard freeze the old turn's count on
  // screen (the stale "Working for Xs" regression). Small backwards jitter
  // (<1.5s) still can't regress the display.
  const prevPerfRef = useRef<ChatPerfPayload | null | undefined>(undefined);
  useEffect(() => {
    const prev = prevPerfRef.current;
    prevPerfRef.current = perf;
    if (!perf) {
      setSec(null);
      return;
    }
    const next = Math.floor(perf.elapsedMs / 1000);
    const isTurnReset = prev != null && perf.elapsedMs + 1500 < prev.elapsedMs;
    setSec((cur) => (isTurnReset || cur == null || next >= cur ? next : cur));
  }, [perf]);

  // Interpolate between snapshots so the displayed second flips on real
  // wall-clock boundaries. Runs while snapshots exist OR while `fallback` is
  // set (a live bubble without perf events — anchored to mount time), so
  // completed bubbles (no perf, not live) never pay for a timer.
  const ticking = perf != null || fallback;
  useEffect(() => {
    if (!ticking) return;
    const iv = window.setInterval(() => {
      const a = anchor.current ?? { baseMs: 0, at: mountedAt.current };
      const interpolated = Math.floor(
        (a.baseMs + Math.max(0, performance.now() - a.at)) / 1000,
      );
      setSec((prev) => (prev == null || interpolated > prev ? interpolated : prev));
    }, 250);
    return () => window.clearInterval(iv);
  }, [ticking]);

  return sec;
}

/** Returns a style object for inline code elements using CSS variable lookups
 *  that work in both light and dark themes (the variables resolve at runtime). */
function useInlineCodeStyle() {
  return useMemo(
    () => ({
      background: "var(--surface-2)",
      padding: "2px 6px",
      borderRadius: "var(--radius-xs)",
      fontFamily: "var(--font-mono)",
      fontSize: "0.9em",
      boxShadow: "var(--glass-rim-soft)",
    }),
    [],
  );
}

function CopyButton({ code }: { code: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      // Clipboard unavailable — silently ignore.
    }
  }, [code]);

  return (
    <button className="ghost copy-code-btn" onClick={handleCopy}>
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

/** djb2 — a tiny stable hash so a JSX block gets a consistent preview id. */
function hashCode(s: string): string {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) | 0;
  return (h >>> 0).toString(36);
}

/** Strictly limit how much of a tool step's code we hand to a `<SyntaxHighlighter>`.
 *  React-Syntax-Highlighter ships a vulnerable dependency tree (refractor / hast)
 *  historically; an extremely long `code` payload from a misbehaving model could
 *  amplify any parser cost. A 200 KB cap is well above any legitimate code block
 *  and bounds the worst case. */
const MAX_CODE_BLOCK_BYTES = 200_000;

/** Chip that opens a ```jsx / ```tsx block as a live preview in the side pane
 *  (Claude-style), instead of rendering it inline in the chat. */
function JsxArtifactChip({
  code,
  lang,
  onPreviewArtifact,
}: {
  code: string;
  lang: "jsx" | "tsx";
  onPreviewArtifact?: (artifact: ChatArtifact) => void;
}) {
  const filename = `Component.${lang}`;
  return (
    <button
      type="button"
      className="chat-artifact-chip chat-jsx-chip"
      title="Open live React preview"
      onClick={(e) => {
        e.currentTarget.blur();
        onPreviewArtifact?.({
          path: `jsx:${lang}:${hashCode(code)}`,
          filename,
          inline: { kind: lang, code },
        });
      }}
    >
      <ReactIcon />
      <span>React preview</span>
    </button>
  );
}

function ReactIcon() {
  return (
    <svg width={13} height={13} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true">
      <circle cx="12" cy="12" r="1.6" fill="currentColor" stroke="none" />
      <ellipse cx="12" cy="12" rx="10" ry="4" />
      <ellipse cx="12" cy="12" rx="10" ry="4" transform="rotate(60 12 12)" />
      <ellipse cx="12" cy="12" rx="10" ry="4" transform="rotate(120 12 12)" />
    </svg>
  );
}

/** Renders `![alt](src)` inside assistant markdown. Remote/data/blob URLs
 *  render directly. LOCAL file references — what the agent produces when it
 *  saves a screenshot or image to disk (`C:\…`, `file:///…`, `/…`) — can never
 *  work as an <img> src here: the CSP allows only 'self' data: blob: https:,
 *  no asset protocol is registered, and a bare path resolves against the app
 *  origin and 404s. So local refs load their bytes over IPC (the same
 *  read_artifact_preview the canvas uses) and render as a data URI. */
function ChatImage({ src, alt }: { src: string; alt?: string }) {
  const isRemote = /^(https?:|data:|blob:)/i.test(src);
  const [dataUri, setDataUri] = useState<string | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    if (isRemote) return;
    let stale = false;
    let path = src.trim();
    const fileMatch = /^file:\/\/\/?(.*)$/i.exec(path);
    if (fileMatch) path = fileMatch[1];
    try {
      path = decodeURIComponent(path);
    } catch {
      // Not URL-encoded (e.g. a raw Windows path with %) — keep it as-is.
    }
    // "file:///C:/…" leaves a leading slash before the drive letter.
    if (/^\/[A-Za-z]:\//.test(path)) path = path.slice(1);
    void readArtifactPreview(path)
      .then((preview) => {
        if (stale) return;
        if (preview?.kind === "image" && preview.dataUri) setDataUri(preview.dataUri);
        else setFailed(true);
      })
      .catch(() => {
        if (!stale) setFailed(true);
      });
    return () => {
      stale = true;
    };
  }, [src, isRemote]);

  if (isRemote || dataUri) {
    return <img src={isRemote ? src : dataUri!} alt={alt ?? ""} />;
  }
  if (failed) {
    return (
      <span style={{ color: "var(--muted, #888)", fontSize: "0.85em" }}>
        {alt || "Image"} — preview unavailable ({src})
      </span>
    );
  }
  return <span style={{ color: "var(--muted, #888)", fontSize: "0.85em" }}>Loading image…</span>;
}

/** Renders a markdown string with syntax-highlighted code fences, mermaid
 *  diagrams and glass-styled links — the assistant's normal answer body. */
function Markdown({
  content,
  onPreviewArtifact,
}: {
  content: string;
  onPreviewArtifact?: (artifact: ChatArtifact) => void;
}) {
  const inlineCodeStyle = useInlineCodeStyle();
  return (
    <div className="chat-markdown">
      <ReactMarkdown
        remarkPlugins={[remarkGfm, remarkMath]}
        rehypePlugins={[rehypeKatex]}
        components={{
          code({ className, children, ...props }) {
            const match = /language-(\w+)/.exec(className || "");
            const rawCode = String(children).replace(/\n$/, "");
            // Cap the code string before handing it to the highlighter so a
            // misbehaving model can't ship a pathologically large payload
            // that amplifies any parser cost in the (historically
            // vulnerable) highlighter dep tree. Truncate cleanly.
            const codeString =
              rawCode.length > MAX_CODE_BLOCK_BYTES
                ? rawCode.slice(0, MAX_CODE_BLOCK_BYTES) + "\n… (truncated)"
                : rawCode;

            // Inline code: no language class and short.
            if (!match && !String(children).includes("\n")) {
              return (
                <code style={inlineCodeStyle} {...props}>
                  {children}
                </code>
              );
            }

            // Mermaid diagrams render as inline SVG, not as highlighted text.
            if (match && match[1] === "mermaid") {
              return (
                <Suspense fallback={<pre className="chat-markdown-mermaid-fallback">{codeString}</pre>}>
                  <MermaidDiagram code={codeString} />
                </Suspense>
              );
            }

            // React/JSX artifacts open as a live preview in the side pane
            // (rendered by ArtifactPreviewPane), not inline in the chat.
            if (match && (match[1] === "jsx" || match[1] === "tsx")) {
              return (
                <JsxArtifactChip
                  code={codeString}
                  lang={match[1] as "jsx" | "tsx"}
                  onPreviewArtifact={onPreviewArtifact}
                />
              );
            }

            // Code block with language.
            return (
              <div className="chat-code-block">
                <div className="chat-code-header">
                  <span className="chat-code-lang">{match ? match[1] : "text"}</span>
                  <CopyButton code={codeString} />
                </div>
                <StepCodeHighlighter code={codeString} language={match ? match[1] : "text"} />
              </div>
            );
          },
          // Images: remote URLs render as-is; local file paths (agent-saved
          // screenshots/images) are loaded over IPC into a data URI — see
          // ChatImage for why a bare path can never render in this webview.
          img({ src, alt }) {
            return <ChatImage src={typeof src === "string" ? src : ""} alt={alt} />;
          },
          // Links open in the built-in browser pane, NOT the system browser:
          // in a Tauri webview a target=_blank navigation falls through to the
          // OS default handler. Intercept the click and route it to the pane.
          a({ href, children }) {
            const isHttp = !!href && /^https?:\/\//i.test(href);
            return (
              <a
                href={href}
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: "var(--accent)" }}
                title={isHttp ? `${href}\n(opens in the built-in browser)` : href}
                onClick={
                  isHttp
                    ? (e) => {
                        e.preventDefault();
                        openInBrowserPane(href!);
                      }
                    : undefined
                }
              >
                {children}
              </a>
            );
          },
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
}

/** One step inside an activity group. Tool steps carry the call's `ToolData`;
 *  think steps (`think` set, `data` null) are reasoning interludes folded into
 *  the SAME group so a turn renders as one outer container instead of
 *  alternating activity/thinking blocks. (`before`/`after` narration slots are
 *  retired: model prose renders as normal message text OUTSIDE the process
 *  region, in source order — captions glued to tool rows read as broken.) */
interface ActivityStep {
  data: ToolData | null;
  done: boolean;
}

/** A grouped run of tool steps, collapsed into one summary line by default. */
interface ActivityGroup {
  steps: ActivityStep[];
}

/** A render block: either a standalone text/think segment (rendered as
 *  before), a collapsed activity group spanning a contiguous tool run, or an
 *  inline diff review card for a file-edit tool call (mockup 01 callout 5). */
type Block =
  | { kind: "text"; text: string }
  | { kind: "think"; text: string; done: boolean }
  | { kind: "activity"; group: ActivityGroup }
  | { kind: "diff"; step: ActivityStep };

/** Walk the parsed segments and collapse the turn's TOOL activity into
 *  ActivityGroup blocks. Thinking (`<think>`) never enters a group: each
 *  reasoning interlude is emitted as its own standalone disclosure beside the
 *  collapsed tool-call summary, so it stays visible without expanding the
 *  group and only tool calls live inside the collapsible.
 *
 *  Boundary rules:
 *  - Text before the first tool/think renders ABOVE the container as markdown.
 *  - A group starts at the first `tool` segment and absorbs every following
 *    `tool` segment — except file-edit tool calls (`kind: "edit"`),
 *    which break out into their own inline diff review card so an edit is
 *    reviewable at a glance instead of buried in the collapsed group. A diff
 *    card flushes the in-progress group, so a turn with edits renders as
 *    alternating activity/diff blocks in call order.
 *  - A `think` segment flushes the in-progress group (if any) and renders as
 *    its own block; a following tool starts a fresh group. A turn thus renders
 *    as alternating think/activity blocks in source order.
 *  - Mid-run prose is NORMAL message text, not tool-row decoration: it closes
 *    the in-progress run and emits as its own text block, so every narration
 *    the model writes renders outside the process region as markdown (the old
 *    behavior glued it to tool rows as tiny captions — unreadable).
 *  - Text trailing the last tool/think is the model's synthesized answer and
 *    renders OUTSIDE the group as markdown, after the summary.
 *  - A turn with thinking but NO tool calls keeps the old behavior: the think
 *    segment stays its own standalone disclosure. */
function groupSegments(segments: Segment[]): Block[] {
  // No tool activity at all → pass through (a lone thinking block stays its
  // own disclosure, text renders as markdown).
  if (!segments.some((s) => s.type === "tool")) {
    return segments.map((seg) =>
      seg.type === "think"
        ? { kind: "think", text: seg.text, done: seg.done }
        : { kind: "text", text: seg.type === "text" ? seg.text : "" },
    );
  }

  const blocks: Block[] = [];
  let steps: ActivityStep[] = [];

  // Close out the in-progress activity group (a diff card splits the run).
  const flushSteps = () => {
    if (steps.length > 0) {
      blocks.push({ kind: "activity", group: { steps } });
      steps = [];
    }
  };

  for (const seg of segments) {
    if (seg.type === "text") {
      // ALL prose — leading, mid-run narration, and the trailing answer —
      // renders as normal markdown outside the process region, in source
      // order. Flush the run so the text lands between tool groups. Text
      // never opens the process region (only tools/think do).
      flushSteps();
      blocks.push({ kind: "text", text: seg.text });
      continue;
    }
    if (seg.type === "tool") {
      // A "result" kind block is the captured output of the preceding shell
      // command — merge it INTO that step instead of creating a separate
      // "Output" row, so expanding the shell command reveals its output.
      if (seg.data?.kind === "result" && steps.length > 0) {
        const prev = steps[steps.length - 1];
        if (prev.data?.kind === "code" && !prev.data.result) {
          prev.data.result = seg.data.result;
          continue;
        }
      }
      const step: ActivityStep = {
        data: seg.data,
        done: seg.done,
      };
      if (seg.data?.kind === "edit" && seg.data.path && seg.data.edit) {
        flushSteps();
        blocks.push({ kind: "diff", step });
      } else if (seg.data?.kind === "result") {
        // A result that didn't merge (no preceding shell step, or the
        // preceding step already has a result) — keep it as its own row so
        // the output is never lost.
        steps.push(step);
      } else {
        steps.push(step);
      }
      continue;
    }
    if (seg.type === "think") {
      // Skip empty think shells (e.g. an opening tag that just started
      // streaming); any pending narration stays held for the next step.
      if (seg.text.length === 0) continue;
      // Pull thinking OUT of the activity group: close any in-progress tool
      // run, then emit the reasoning as its own disclosure beside the
      // collapsed tool-call summary (not buried inside it). A following tool
      // starts a fresh group, so a turn renders as alternating
      // think/activity blocks in source order.
      flushSteps();
      blocks.push({ kind: "think", text: seg.text, done: seg.done });
      continue;
    }
  }

  flushSteps();
  return blocks;
}

/** Strip attachment markers and think blocks from user content so the inline
 *  editor shows the raw text the user originally typed, not display-only
 *  markers the UI injected. */
function cleanForEdit(content: string): string {
  return content
    .replace(/\n\n\[Attached (?:image|file):[^\n]*\]/g, "")
    .replace(/^\[Attached (?:image|file):[^\n]*\]\n*/gm, "")
    .replace(/^.*?```(?:thinking|think)\n[\s\S]*?\n```\n*/gm, "")
    .trim();
}

function MessageBubbleInner({
  message,
  live,
  onEdit,
  onRepeat,
  onDelete,
  superseded,
  segmentStart,
  artifacts,
  onPreviewArtifact,
  msgId,
  livePerf,
}: Props) {
  const isUser = message.role === "user";
  // Inline edit-to-fork state: when the user clicks Edit on a user bubble, we
  // swap the content for a textarea and "Save & Submit" re-runs the turn.
  const [editing, setEditing] = useState(false);
  const [draftText, setDraftText] = useState(message.content);

  const openEditor = useCallback(() => {
    setDraftText(cleanForEdit(message.content));
    setEditing(true);
  }, [message.content]);

  // Save submits the edited content through onEdit (the caller forks the
  // branch + re-sends), then closes the editor.
  const submitEdit = useCallback(() => {
    const text = draftText.trim();
    if (!text || !onEdit) return;
    onEdit(text);
    setEditing(false);
  }, [draftText, onEdit]);

  // Per-turn git checkpoints attached to this message (positive ids only —
  // the optimistic in-flight bubble has a negative id and never has one).
  const msgCheckpoints = useChatStore((s) =>
    !isUser && msgId != null && msgId > 0 ? s.checkpointsByMessage[msgId] : undefined,
  ) ?? [];

  // Parse attachment markers (e.g. "[Attached image: x]") out of the content
  // so they render as visual cards above the text instead of inline strings.
  // Live attachments (optimistic message) carry image base64 for thumbnails.
  const { attachments: msgAttachments, text: cleanContent } = parseAttachments(
    message.content,
    message.attachments,
  );

  // PERF (PERFORMANCE_AUDIT.md F8): memoize the parse → group chain by
  // content. Previously a `streaming` flip (or any parent re-render) re-ran
  // parseSegments + groupSegments even with identical content. During active
  // streaming content changes per flush anyway, so the memo costs nothing.
  // User messages are rendered verbatim; assistant messages are split into
  // reasoning / tool-call / answer segments (Claude-style process view).
  const segments: Segment[] = useMemo<Segment[]>(
    () => (isUser ? [{ type: "text", text: cleanContent }] : parseSegments(cleanContent)),
    [isUser, cleanContent],
  );

  // Copy action yields the visible answer text only (no process markup).
  const plainText = useMemo(
    () =>
      segments
        .filter((s): s is Extract<Segment, { type: "text" }> => s.type === "text")
        .map((s) => s.text)
        .join("")
        .trim(),
    [segments],
  );

  // Group the turn into ordered render blocks (text / think / activity / diff).
  const blocks = useMemo(() => (isUser ? null : groupSegments(segments)), [isUser, segments]);

  // Live "Working for Xs" seconds — locally interpolated between chat:perf
  // snapshots so second flips land on wall-clock boundaries; harness turns
  // (no perf events) tick from bubble mount via the fallback. Hook must stay
  // ABOVE the compaction early return below (rules of hooks).
  const liveElapsedSec = useLiveElapsedSec(live ? livePerf : null, !!live);

  // A persisted compaction-summary row renders as a low-weight "earlier context
  // compacted" marker (not a real bubble) so the user understands why
  // scrolling back shows condensed rather than verbatim detail. Tapping
  // reveals the actual summary text that replaced the original turns.
  // Sentinel must match the `COMPACTED_PREFIX` constant in
  // src-tauri/src/chat/compaction.rs. NOTE: this early return must stay BELOW
  // the hooks above (rules of hooks).
  const COMPACTED_PREFIX = "[compacted context]";
  if (message.role === "system" && message.content.trimStart().startsWith(COMPACTED_PREFIX)) {
    const summary = message.content.trimStart().slice(COMPACTED_PREFIX.length).replace(/^[\s:\n]+/, "");
    return <CompactedContextMarker summary={summary} />;
  }

  // Partition the assistant turn into [process blocks] [text]. Process kinds
  // (think / activity / diff) ALL live inside the single collapsible
  // "Worked for Xs" row at the TOP of the bubble; the model's text (intro +
  // answer) renders below it in source order. (Thinking used to render as
  // standalone disclosures interleaved with the text, which read as three
  // separate blocks after the turn ended.)
  let hasProcess = false;
  if (blocks) {
    for (const b of blocks) {
      if (b.kind === "activity" || b.kind === "diff" || b.kind === "think") {
        hasProcess = true;
        break;
      }
    }
  }

  // Aggregate process-level state: is anything still live and how many steps
  // ran. (The old "current action" label is gone — the expanded body already
  // shows the live steps, so a separate action line was redundant.)
  let processLive = false;
  let processStepCount = 0;
  const processToolSteps: ActivityStep[] = [];
  const fileChanges: { path: string; edit: EditPayload }[] = [];
  if (hasProcess && blocks) {
    for (const b of blocks) {
      if (b.kind === "activity") {
        for (const s of b.group.steps) {
          processStepCount++;
          processToolSteps.push(s);
          if (!s.done) processLive = true;
        }
      } else if (b.kind === "diff") {
        processStepCount++;
        processToolSteps.push({ data: b.step.data, done: b.step.done });
        if (!b.step.done) processLive = true;
      } else if (b.kind === "think" && !b.done) {
        processLive = true;
      }
    }
  }
  // File changes span the whole turn (diff blocks are always in the region).
  if (blocks) {
    for (const b of blocks) {
      if (b.kind === "diff" && b.step.data?.path && b.step.data?.edit) {
        fileChanges.push({ path: b.step.data.path, edit: b.step.data.edit });
      }
    }
  }
  // The collapsed row's label is ALWAYS the timer: "Working for Xs" while
  // streaming, "Worked for Xs" once the duration is known. A cancelled stream
  // has no duration — the label falls back to a plain "Worked", never to the
  // last running tool's summary (a cut-off turn must not retitle itself
  // "Running shell command" after the fact).
  const processLabel = live
    ? (liveElapsedSec != null
        ? `Working for ${formatDuration(liveElapsedSec)}`
        : "Working")
    : message.durationSec != null
      ? `Worked for ${formatDuration(message.durationSec)}`
      : "Worked";

  // Detect if this assistant message contains a plan section
  const planSection = !isUser ? detectPlan(message.content) : null;

  return (
    <>
      {segmentStart && <div className="superseded-divider">— edited —</div>}
      <div
        className={`chat-bubble${isUser ? " user" : " assistant"}${superseded ? " superseded" : ""}${editing ? " editing" : ""}`}
        data-msg-id={msgId}
      >
        {superseded && (
          <span className="superseded-tag">previous version</span>
        )}
        {msgAttachments.length > 0 && <MessageAttachments attachments={msgAttachments} />}
        <div className="chat-bubble-inner">
          {planSection && (
            <PlanBanner title={planSection.title} summary={planSection.summary} full={planSection.full} />
          )}
          {!isUser && !hasProcess && (live || message.durationSec != null) && (
            <div className="assistant-message-header">
              {/* Pure-text turn (nothing to expand): plain Working/Worked-for
                 header, same style the process turns use. */}
              {live
                ? (liveElapsedSec != null
                    ? `Working for ${formatDuration(liveElapsedSec)}`
                    : "Working")
                : `Worked for ${formatDuration(message.durationSec ?? 0)}`}
            </div>
          )}
          {editing && isUser ? (
            <div className="message-edit-editor">
              <textarea
                value={draftText}
                onChange={(e) => setDraftText(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Escape") setEditing(false);
                  else if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) submitEdit();
                }}
                autoFocus
                rows={Math.max(3, Math.min(8, draftText.split("\n").length))}
              />
              <div className="message-edit-actions">
                <button type="button" className="ghost" onClick={() => setEditing(false)}>
                  Cancel
                </button>
                <button type="button" className="message-edit-save" onClick={submitEdit}>
                  Save &amp; Submit
                </button>
              </div>
            </div>
          ) : isUser
            ? cleanContent.trim().length > 0 && (
                <Markdown content={cleanContent} onPreviewArtifact={onPreviewArtifact} />
              )
            : hasProcess
            ? (() => {
                // The "Working for Xs / Worked for Xs" header is ALWAYS the
                // first line of the assistant turn — narration that arrived
                // before the first tool call ("Let me read the page…") used
                // to push the header below itself, so the same turn shape
                // rendered differently depending on whether the model chose
                // to speak first. Everything up to the last process block
                // (intro prose included, in source order) now lives INSIDE
                // the expansion; only the final answer renders below the row.
                if (!blocks) return null;
                const lastProc = blocks.reduce(
                  (acc, b, i) => (b.kind !== "text" ? i : acc),
                  -1,
                );
                const inside = blocks.slice(0, lastProc + 1);
                const trailing = blocks.slice(lastProc + 1);
                const textBlock = (b: Block, key: string) =>
                  b.kind === "text" && b.text.trim().length > 0 ? (
                    <Markdown key={key} content={b.text} onPreviewArtifact={onPreviewArtifact} />
                  ) : null;
                return (
                  <>
                    <ProcessSummary live={live === true} label={processLabel}>
                      {inside.map((b, i) => renderProcessBlock(b, i, onPreviewArtifact))}
                    </ProcessSummary>
                    {trailing.map((b, i) => textBlock(b, `trail:${i}`))}
                  </>
                );
              })()
            /* Pure-text turn: flat markdown, nothing to expand. */
            : blocks!.map((b, i) =>
                b.kind === "text" && b.text.trim().length > 0
                  ? <Markdown key={`flat:${i}`} content={b.text} onPreviewArtifact={onPreviewArtifact} />
                  : null,
              )}
        {/* Consolidated per-turn changes row: "N files changed +adds −dels"
            with an Undo (checkpoint restore) button; expanding lists the
            files with Review / Open. Replaces the old stacked
            FilesChangedSummary + artifact chip + CheckpointChip rows.
            Shown only once the turn has ENDED — while the model is still
            streaming the file set is incomplete and the row would flicker
            in with partial counts. */}
        {!isUser &&
          !live &&
          (fileChanges.length > 0 || msgCheckpoints.length > 0) && (
            <TurnChangesRow
              files={fileChanges}
              checkpoints={msgCheckpoints}
              artifacts={artifacts}
              onPreviewArtifact={onPreviewArtifact}
            />
          )}
        {/* Artifact chips for files the changes row already covers would be
            duplicates — only chip the leftovers (rare non-write artifacts). */}
        {!isUser && artifacts && artifacts.length > 0 && (
          <MessageArtifacts
            artifacts={artifacts.filter(
              (a) => !fileChanges.some((f) => sameTurnFile(a.path, f.path)),
            )}
            onPreviewArtifact={onPreviewArtifact}
          />
        )}
      </div>
      {!live && (
        <MessageActions
          content={plainText || message.content}
          onEdit={isUser ? openEditor : undefined}
          onRepeat={onRepeat}
          onDelete={onDelete}
        />
      )}
    </div>
    </>
  );
}

// ---- Plan detection & banner ----

const PLAN_PATTERNS = [
  /^#+\s*(Plan|Planning|Approach|Strategy|Implementation Plan)\b/im,
  /^#+\s*Steps\s+(?:to|for|of)\b/im,
  /^(?:Here(?:'s| is) (?:my |the |a )?plan\b)/im,
  /^(?:Let me (?:plan|think about|outline|break down))/im,
  /^(?:I(?:'ll| will) (?:plan|break|outline|do the following))/im,
  /^(?:My plan (?:is|:))/im,
];

interface PlanInfo { title: string; summary: string; full: string; }

function detectPlan(content: string): PlanInfo | null {
  const cleaned = content.replace(/<think>[\s\S]*?<\/think>/gi, "").trim();
  if (cleaned.length < 50) return null;
  // Avoid false positives on directory listings / file trees: a bare file tree
  // has many short lines (paths) but few words. Require the candidate region
  // to have at least 4 prose lines (≥ 4 words each) to qualify as a plan.
  const hasProseBody = (text: string): boolean => {
    const lines = text.split("\n").filter((l) => {
      const t = l.trim();
      if (!t) return false;
      // Skip headings, list markers, code fences, table pipes.
      if (/^[#>\-*`|]/.test(t)) return false;
      return t.split(/\s+/).length >= 4;
    });
    return lines.length >= 4;
  };

  for (const pattern of PLAN_PATTERNS) {
    const m = pattern.exec(cleaned);
    if (m) {
      const start = m.index;
      const after = cleaned.slice(start);
      const nextSection = after.slice(m[0].length).search(/^#+\s/m);
      const full = nextSection !== -1
        ? after.slice(0, m[0].length + nextSection).trim()
        : after.trim();
      if (!hasProseBody(full)) continue; // likely a file listing, not a plan
      const title = after.split("\n")[0].replace(/^#+\s*/, "").replace(/[*_]/g, "").trim().slice(0, 60);
      // First 2-3 lines as summary
      const lines = full.split("\n").filter((l) => l.trim());
      const summary = lines.slice(1, 4).join(" ").replace(/[*_#]/g, "").trim().slice(0, 120);
      return { title, summary, full };
    }
  }
  return null;
}

function PlanBanner({ title, summary, full }: PlanInfo) {
  const [open, setOpen] = useState(false);
  const setPlanCanvas = useUiStore((s) => s.setPlanCanvas);
  const openPlanTab = useUiStore((s) => s.openPlanTab);

  const openInPlanTab = () => {
    setPlanCanvas(full, title);
    openPlanTab();
  };

  return (
    <div className="chat-plan-banner">
      <div className="chat-plan-banner-header" onClick={() => setOpen(!open)}>
        <span className="chat-plan-banner-icon">📋</span>
        <span className="chat-plan-banner-title">Plan: {title}</span>
        <span className="chat-plan-banner-chevron">{open ? "▾" : "▸"}</span>
      </div>
      {open && (
        <div className="chat-plan-banner-body">
          <div className="chat-plan-banner-summary">{summary}</div>
          <button className="chat-plan-banner-canvas-btn" onClick={openInPlanTab}>
            Open full plan →
          </button>
        </div>
      )}
    </div>
  );
}

// Memoized: a bubble re-parses its markdown (react-markdown + katex) on every
// render, so re-rendering the whole list on each streaming token or composer
// keystroke made long chats laggy. ChatView keeps the `items` array (and the
// per-item callbacks) reference-stable via useMemo, so an unchanged bubble
// now skips re-render entirely.
export const MessageBubble = memo(MessageBubbleInner);