// A single chat message bubble. User messages right-aligned, assistant
// left-aligned. Renders markdown via react-markdown with syntax highlighting.
// Streaming token-by-token updates are debounced to ~50ms by the caller —
// this component simply accepts a `content: string` prop and renders it.
import { useCallback, useMemo, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import type { ChatMessage } from "../../lib/ipc";
import type { ChatArtifact } from "../../state/chat";
import { MermaidDiagram } from "./MermaidDiagram";

interface Props {
  message: ChatMessage;
  /** True for the in-progress streaming bubble — hides the action bar. */
  live?: boolean;
  /** When provided (user messages), shows an "Edit" action that loads the
   *  message text back into the composer. */
  onEdit?: (content: string) => void;
  /** When provided (assistant messages), shows a "Regenerate" action. */
  onRepeat?: () => void;
  /** Artifacts generated by this message, shown as clickable chips below it. */
  artifacts?: ChatArtifact[];
  /** Open an artifact in the preview pane (used by the inline chips). */
  onPreviewArtifact?: (artifact: ChatArtifact) => void;
}

// --- Inline SVG icons (Claude-style, stroke-based, currentColor). ---
const iconProps = {
  width: 15,
  height: 15,
  viewBox: "0 0 24 24",
  fill: "none",
  stroke: "currentColor",
  strokeWidth: 2,
  strokeLinecap: "round" as const,
  strokeLinejoin: "round" as const,
};

function CopyIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <rect x="9" y="9" width="13" height="13" rx="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

function CheckIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <path d="M20 6 9 17l-5-5" />
    </svg>
  );
}

function EditIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <path d="M12 20h9" />
      <path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4Z" />
    </svg>
  );
}

function RepeatIcon() {
  return (
    <svg {...iconProps} aria-hidden="true">
      <path d="M3 2v6h6" />
      <path d="M3 13a9 9 0 1 0 3-7.7L3 8" />
    </svg>
  );
}

function FileIcon() {
  return (
    <svg
      width={13}
      height={13}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>
  );
}

/** Row of clickable chips for the files an assistant message produced. */
function MessageArtifacts({
  artifacts,
  onPreviewArtifact,
}: {
  artifacts: ChatArtifact[];
  onPreviewArtifact?: (artifact: ChatArtifact) => void;
}) {
  return (
    <div className="chat-msg-artifacts" aria-label="Generated files">
      {artifacts.map((a) => (
        <button
          key={a.path}
          type="button"
          className="chat-artifact-chip"
          title={`Preview ${a.filename}`}
          onClick={(e) => {
            e.currentTarget.blur();
            onPreviewArtifact?.(a);
          }}
        >
          <FileIcon />
          <span>{a.filename}</span>
        </button>
      ))}
    </div>
  );
}

/** Per-message action bar (Claude-style icons): copy for every message, edit
 *  for user messages, regenerate for assistant messages. Appears on hover
 *  under the bubble. */
function MessageActions({
  content,
  onEdit,
  onRepeat,
}: {
  content: string;
  onEdit?: (content: string) => void;
  onRepeat?: () => void;
}) {
  const [copied, setCopied] = useState(false);
  const copy = useCallback(
    async (e: React.MouseEvent<HTMLButtonElement>) => {
      // Drop focus so the hover-only action bar doesn't stay pinned open
      // after a mouse click.
      e.currentTarget.blur();
      try {
        await navigator.clipboard.writeText(content);
        setCopied(true);
        setTimeout(() => setCopied(false), 1800);
      } catch {
        // Clipboard unavailable — silently ignore.
      }
    },
    [content],
  );

  return (
    <div className="chat-msg-actions">
      <button
        className="chat-msg-action"
        onClick={copy}
        title={copied ? "Copied" : "Copy message"}
        aria-label="Copy message"
      >
        {copied ? <CheckIcon /> : <CopyIcon />}
      </button>
      {onRepeat && (
        <button
          className="chat-msg-action"
          onClick={(e) => {
            e.currentTarget.blur();
            onRepeat();
          }}
          title="Regenerate response"
          aria-label="Regenerate response"
        >
          <RepeatIcon />
        </button>
      )}
      {onEdit && (
        <button
          className="chat-msg-action"
          onClick={(e) => {
            e.currentTarget.blur();
            onEdit(content);
          }}
          title="Edit message"
          aria-label="Edit message"
        >
          <EditIcon />
        </button>
      )}
    </div>
  );
}

/** Claude-style pre-token "thinking" animation: three pulsing dots shown
 *  while the request is in flight but no content has streamed yet. */
export function TypingIndicator() {
  return (
    <div className="chat-bubble assistant">
      <div className="chat-bubble-inner">
        <div className="chat-typing" aria-label="Assistant is responding" role="status">
          <span className="chat-typing-dot" />
          <span className="chat-typing-dot" />
          <span className="chat-typing-dot" />
        </div>
      </div>
    </div>
  );
}

/** Splits a `<think>…</think>` reasoning block (streamed by reasoning
 *  models) off the front of the message. `done` is false while the closing
 *  tag hasn't arrived yet (still thinking). */
function splitThinking(content: string): {
  thinking: string | null;
  done: boolean;
  rest: string;
} {
  const match = /^\s*<think>([\s\S]*?)(?:<\/think>|$)/.exec(content);
  if (!match) return { thinking: null, done: true, rest: content };
  const done = match[0].includes("</think>");
  return {
    thinking: match[1].trim(),
    done,
    rest: content.slice(match[0].length).trim(),
  };
}

function ThinkingBlock({ thinking, done }: { thinking: string; done: boolean }) {
  const [open, setOpen] = useState(false);
  return (
    <div className={`chat-thinking${done ? "" : " live"}`}>
      <button
        className="chat-thinking-toggle"
        onClick={() => setOpen((o) => !o)}
        title={open ? "Hide thinking" : "Show thinking"}
      >
        <span className="chat-thinking-icon">✵</span>
        {done ? "Thought process" : "Thinking…"}
        <span className={`chat-thinking-chevron${open ? " open" : ""}`}>›</span>
      </button>
      {open && <div className="chat-thinking-body">{thinking}</div>}
    </div>
  );
}

/** Returns a style object for inline code elements using CSS variable lookups
 *  that work in both light and dark themes (the variables resolve at runtime). */
function useInlineCodeStyle() {
  return useMemo(
    () => ({
      background: "var(--surface-2)",
      padding: "2px 6px",
      borderRadius: "var(--radius-xs)",
      fontFamily: "var(--font-mono)",
      fontSize: "0.9em",
      boxShadow: "var(--glass-rim-soft)",
    }),
    [],
  );
}

function CopyButton({ code }: { code: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      // Clipboard unavailable — silently ignore.
    }
  }, [code]);

  return (
    <button className="ghost copy-code-btn" onClick={handleCopy}>
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

export function MessageBubble({
  message,
  live,
  onEdit,
  onRepeat,
  artifacts,
  onPreviewArtifact,
}: Props) {
  const isUser = message.role === "user";
  const inlineCodeStyle = useInlineCodeStyle();
  const { thinking, done, rest } = isUser
    ? { thinking: null, done: true, rest: message.content }
    : splitThinking(message.content);

  return (
    <div className={`chat-bubble${isUser ? " user" : " assistant"}`}>
      <div className="chat-bubble-inner">
        {thinking !== null && thinking.length > 0 && (
          <ThinkingBlock thinking={thinking} done={done} />
        )}
        <div className="chat-markdown">
        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
          components={{
            code({ className, children, ...props }) {
              const match = /language-(\w+)/.exec(className || "");
              const codeString = String(children).replace(/\n$/, "");

              // Inline code: no language class and short.
              if (!match && !String(children).includes("\n")) {
                return (
                  <code style={inlineCodeStyle} {...props}>
                    {children}
                  </code>
                );
              }

              // Mermaid diagrams render as inline SVG, not as highlighted text.
              if (match && match[1] === "mermaid") {
                return <MermaidDiagram code={codeString} />;
              }

              // Code block with language.
              return (
                <div className="chat-code-block">
                  <div className="chat-code-header">
                    <span className="chat-code-lang">
                      {match ? match[1] : "text"}
                    </span>
                    <CopyButton code={codeString} />
                  </div>
                  <SyntaxHighlighter
                    style={{}}
                    language={match ? match[1] : "text"}
                    PreTag="div"
                    customStyle={{
                      margin: 0,
                      background: "transparent",
                      padding: "12px 16px",
                      fontSize: "12px",
                      fontFamily: "var(--font-mono)",
                      lineHeight: 1.5,
                      overflowX: "auto",
                    }}
                    codeTagProps={{
                      style: {
                        fontFamily: "var(--font-mono)",
                      },
                    }}
                  >
                    {codeString}
                  </SyntaxHighlighter>
                </div>
              );
            },
            // Render links with target=_blank and glass-appropriate styling.
            a({ href, children }) {
              return (
                <a
                  href={href}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ color: "var(--accent)" }}
                >
                  {children}
                </a>
              );
            },
          }}
        >
          {rest}
        </ReactMarkdown>
        </div>
        {!isUser && artifacts && artifacts.length > 0 && (
          <MessageArtifacts
            artifacts={artifacts}
            onPreviewArtifact={onPreviewArtifact}
          />
        )}
      </div>
      {!live && (
        <MessageActions
          content={message.content}
          onEdit={onEdit}
          onRepeat={onRepeat}
        />
      )}
    </div>
  );
}