// Settings → Local Models → "Images" tab: local image generation — the
// sd.cpp analog of the speech panels. The sd-server engine installs through
// the shared Server builds card (CUDA / Vulkan / CPU builds), model files
// download through the shared Model-Market engine into
// <models dir>/image-gen/, and the "try it" box exercises the whole pipeline
// without leaving settings. Backend contract:
// src-tauri/src/commands/image_gen.rs.
import { useEffect, useRef, useState } from "react";
import {
  cancelModelDownload,
  type FamilyPlan,
  imageGenSelect,
  imageGenSetDefault,
  imageGenSetDevice,
  imageGenSetFileLayout,
  imageGenSetFileRole,
  imageGenSetServerPath,
  imageGenStart,
  imageGenStatus,
  imageGenStop,
  imageGenFamilyPlans,
  imageGenUseFamily,
  imageGenerate,
  onModelDownloadProgress,
  startModelDownload,
  toastError,
  toastSuccess,
  type GeneratedImage,
  type ImageCatalogEntry,
  type ImageGenStatus as ImageGenStatusData,
  type DetectedImageFile,
  type ImageLayout,
  type ImageModelRole,
  type PerDownloadState,
} from "../../lib/ipc";
import { formatBytes, shortName } from "../../lib/format";
import { IMAGE_GEN_PANEL_OWNER, useImageGenStore } from "../../state/imageGenStore";
import { Modal } from "../common/Modal";
import { ServerBuildsCard } from "./ServerBuildsCard";

const DEVICES: { id: string; label: string }[] = [
  { id: "auto", label: "Auto" },
  { id: "vulkan", label: "Vulkan" },
  { id: "cpu", label: "CPU" },
];

/** Display repo per role (progress toast / download bookkeeping only). */
const REPO_BY_ROLE: Record<string, string> = {
  diffusion: "leejet/Z-Image-Turbo-GGUF",
  "text-encoder": "unsloth/Qwen3-4B-Instruct-2507-GGUF",
  vae: "black-forest-labs/FLUX.1-schnell",
};

/** Package display names (backend owns the authoritative label; this is the
 *  card title prefix). */
const FAMILY_LABELS: Record<string, string> = {
  "z-image-turbo": "Z-Image Turbo",
  sd15: "SD 1.5",
  "sdxl-base": "SDXL Base",
  "sdxl-turbo": "SDXL Turbo",
  dreamshaper: "DreamShaper 8",
};
const familyLabel = (f: string) => FAMILY_LABELS[f] ?? f;

/** One best package per GPU VRAM tier (the model's comfortable floor).
 *  Clicking a tier installs & activates that package — the shared-component
 *  dedupe means even a 4GB-card user downloads ONE file, not four. */
const GPU_TIERS: { range: string; family: string; variant?: string; short: string }[] = [
  { range: "≤4 GB", family: "dreamshaper", short: "DreamShaper 8" },
  { range: "4–7 GB", family: "z-image-turbo", variant: "image/diffusion-z-image-turbo-q4_0", short: "Z-Image Turbo" },
  { range: "8 GB", family: "z-image-turbo", variant: "image/diffusion-z-image-turbo-q6_k", short: "Z-Image Q6_K" },
  { range: "9–12 GB", family: "sdxl-turbo", short: "SDXL Turbo" },
  { range: "13 GB+", family: "sdxl-base", short: "SDXL Base" },
];

/** Card swatch hues per family (visual identity in the preset grid). */
/** Sample images actually generated by each model — official HF/CivitAI
 *  samples bundled into the app (public/model-samples, ~110KB total) so the
 *  cards show what a model makes without any runtime fetch. Disk models map
 *  by filename; anything unknown falls back to the gradient tile. */
/** Fallback tile hues for disk models with no known sample. */
const FAMILY_SWATCHES: Record<string, string[]> = {
  disk: ["#1f2937", "#374151", "#6b7280", "#d1d5db"],
};

const FAMILY_SAMPLES: Record<string, string> = {
  "z-image-turbo": "model-samples/z-image.jpg",
  sd15: "model-samples/sd15.jpg",
  "sdxl-base": "model-samples/sdxl-base.jpg",
  "sdxl-turbo": "model-samples/sdxl-turbo.jpg",
  dreamshaper: "model-samples/dreamshaper.jpg",
};

/** Disk files identified by filename fragment → their sample. */
const DISK_SAMPLES: [RegExp, string][] = [
  [/pony/i, "model-samples/pony.jpg"],
  [/cyberrealistic/i, "model-samples/cyberrealistic.jpg"],
  [/klein/i, "model-samples/flux2-klein.jpg"],
];

function sampleFor(family: string, label: string): string | null {
  const direct = FAMILY_SAMPLES[family];
  if (direct) return direct;
  if (family.startsWith("disk:")) {
    for (const [re, src] of DISK_SAMPLES) {
      if (re.test(label) || re.test(family)) return src;
    }
  }
  return null;
}

export function ImageGenPanel() {
  const [status, setStatus] = useState<ImageGenStatusData | null>(null);
  const [busy, setBusy] = useState(false);
  const [detailId, setDetailId] = useState<string | null>(null);
  const [pathInput, setPathInput] = useState("");
  const [downloads, setDownloads] = useState<Record<string, PerDownloadState>>({});
  const [tryPrompt, setTryPrompt] = useState("");
  const [tryImage, setTryImage] = useState<GeneratedImage | null>(null);

  const refresh = () => {
    void imageGenStatus().then(setStatus).catch(() => {});
  };
  useEffect(refresh, []);

  // Live download bars (same stream the Model Market and Speech use). The
  // success/error TOASTS are filtered to image-related ids: this stream also
  // carries llama/STT/TTS/engine downloads, and toasting "Image model
  // installed" for those from the Images tab is noise (TtsPanel filters the
  // same way).
  const imageDownloadIdsRef = useRef<Set<string>>(
    new Set(["image-sd-cuda", "image-sd-vulkan", "image-sd-cpu"]),
  );
  useEffect(() => {
    imageDownloadIdsRef.current = new Set([
      ...(status?.catalog ?? []).map((c) => c.id),
      "image-sd-cuda",
      "image-sd-vulkan",
      "image-sd-cpu",
    ]);
  }, [status]);
  useEffect(() => {
    let stale = false;
    let unlisten: (() => void) | null = null;
    void onModelDownloadProgress((p) => {
      if (stale) return;
      setDownloads((prev) => ({
        ...prev,
        [p.id]: { state: p.state, downloaded: p.downloadedBytes, total: p.totalBytes ?? null },
      }));
      if (!imageDownloadIdsRef.current.has(p.id)) return;
      if (p.state === "done") {
        toastSuccess("Image model installed");
        refresh();
      }
      if (p.state === "error" && p.error) {
        toastError("Image model download failed", p.error);
      }
    }).then((u) => {
      if (stale) u();
      else unlisten = u;
    });
    return () => {
      stale = true;
      unlisten?.();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleStart = async () => {
    setBusy(true);
    try {
      const s = await imageGenStart();
      setStatus(s);
      toastSuccess(`Image server running on port ${s.port}`);
    } catch (err) {
      toastError("Could not start the image server", err);
    } finally {
      setBusy(false);
      refresh();
    }
  };

  const handleStop = async () => {
    setBusy(true);
    try {
      await imageGenStop();
    } catch (err) {
      toastError("Could not stop the image server", err);
    } finally {
      setBusy(false);
      refresh();
    }
  };

  const handleDevice = async (device: string) => {
    try {
      // The backend stops any running server: it belongs to the previous
      // binary, and generation lazy-starts the new one on demand.
      await imageGenSetDevice(device);
    } catch (err) {
      toastError("Could not switch the image device", err);
    } finally {
      refresh();
    }
  };

  const handleSavePath = async () => {
    try {
      await imageGenSetServerPath(pathInput.trim() || null);
      refresh();
    } catch (err) {
      toastError("Could not save the sd-server path", err);
    }
  };

  const handleSetDefault = async (path: string, layout: ImageLayout, label: string) => {
    try {
      await imageGenSetDefault(path, layout);
      toastSuccess(`${label} is now the default image model`);
      refresh();
    } catch (err) {
      toastError("Could not set the default image model", err);
    }
  };

  const handleFileRole = async (path: string, role: ImageModelRole | null) => {
    try {
      await imageGenSetFileRole(path, role);
      refresh();
    } catch (err) {
      toastError("Could not save the file role", err);
    }
  };

  const handleFileLayout = async (path: string, layout: ImageLayout | null) => {
    try {
      await imageGenSetFileLayout(path, layout);
      refresh();
    } catch (err) {
      toastError("Could not save the file layout", err);
    }
  };

  const handleSelect = async (kind: "text-encoder" | "vae", path: string | null) => {
    try {
      await imageGenSelect(kind, path);
      refresh();
    } catch (err) {
      toastError("Could not switch the selection", err);
    }
  };

  const handleDownload = (m: { id: string; filename: string; downloadUrl: string; role: string }) => {
    void startModelDownload({
      id: m.id,
      repoId: REPO_BY_ROLE[m.role] ?? "huggingface.co",
      filename: m.filename,
      downloadUrl: m.downloadUrl,
      expectedSha256: undefined,
      destDir: status?.imageDir ?? undefined, // <models>/image-gen — status scans it
    }).catch((err) => toastError(`Couldn't start download: ${m.filename}`, err));
  };

  const handleTry = async () => {
    if (!tryPrompt.trim()) return;
    // Mark the run as panel-owned BEFORE its first store event: the chat
    // panes must never render this generation in their message flow.
    useImageGenStore.getState().arm(IMAGE_GEN_PANEL_OWNER);
    setBusy(true);
    setTryImage(null);
    try {
      const img = await imageGenerate(tryPrompt.trim());
      setTryImage(img);
    } catch (err) {
      toastError("Image generation failed", err);
    } finally {
      // Drop the pre-claim unconditionally: a completed generation consumed
      // it at its first event (pendingOwner is null by now), and a failure
      // that fired BEFORE any event must not leave the sentinel armed —
      // otherwise the NEXT CHAT generation's preview gets swallowed into a
      // session id no pane can claim.
      useImageGenStore.getState().disarm();
      setBusy(false);
      refresh();
    }
  };

  /** One row in a kind group: a catalog entry or a detected manual file,
   *  normalized so the group renderer can treat them alike. */
  type GroupRow = {
    key: string;
    /** Selection identity: models-root-relative path. */
    path: string;
    name: string;
    sub: string;
    sizeBytes: number;
    layout?: ImageLayout;
    source: "catalog" | "manual";
    installed: boolean;
    selected: boolean;
    recommended?: boolean;
    download?: { id: string; downloadUrl: string; filename: string; role: string };
    manual?: DetectedImageFile;
  };

  const buildGroup = (role: ImageModelRole): GroupRow[] => {
    if (!status) return [];
    // The effective encoder/VAE resolves wherever the file actually lives
    // (a copy in `flux-encoders/` counts), so catalog rows must compare by
    // FILENAME, not by the download path shape.
    const depSelected = (filename: string) =>
      [status.encoderPath, status.vaePath].some(
        (p) => p === filename || p?.endsWith(`/${filename}`),
      );
    const catalogRows: GroupRow[] = status.catalog
      .filter((m) => m.role === role)
      .map((m) => ({
        key: m.id,
        path: `image-gen/${m.filename}`,
        name: m.label,
        sub: m.note,
        sizeBytes: m.sizeBytes,
        layout: m.layout as ImageLayout,
        source: "catalog" as const,
        installed: m.installed,
        selected:
          role === "diffusion" ? m.isDefault : depSelected(m.filename),
        recommended: m.recommended,
        download: {
          id: m.id,
          downloadUrl: m.downloadUrl,
          filename: m.filename,
          role: m.role,
        },
      }));
    const manualRows: GroupRow[] = status.detected
      .filter((f) => f.role === role)
      .map((f) => ({
        key: f.path,
        path: f.path,
        name: f.name,
        sub: f.path,
        sizeBytes: f.sizeBytes,
        layout: (f.layout ?? "split") as ImageLayout,
        source: "manual" as const,
        installed: true,
        selected:
          role === "diffusion"
            ? status.defaultModel === f.path
            : status.encoderPath === f.path || status.vaePath === f.path,
        manual: f,
      }));
    return [...catalogRows, ...manualRows];
  };

  const diffusionRows = buildGroup("diffusion");
  const encoderRows = buildGroup("text-encoder");
  const vaeRows = buildGroup("vae");

  /** Model PACKAGES: a family = diffusion (with its quant variants) + the
   *  encoder/VAE it needs, rendered from the BACKEND plan so what the card
   *  shows (reuse vs download vs already active) is exactly what the use
   *  command will do. Detected single files on disk (Pony, Cyberrealistic,
   *  …) get their own one-click cards below. */
  const [plans, setPlans] = useState<FamilyPlan[]>([]);
  const [variantPick, setVariantPick] = useState<Record<string, string>>({});
  useEffect(() => {
    void imageGenFamilyPlans().then(setPlans).catch(() => {});
  }, [status]);
  const pickedVariant = (p: FamilyPlan) =>
    variantPick[p.family] ?? p.diffusionId;
  const pickedEntry = (p: FamilyPlan) =>
    p.variants.find((v) => v.id === pickedVariant(p)) ?? p.variants[0];
  const planMissing = (p: FamilyPlan) =>
    (pickedEntry(p)?.action === "download" ? 1 : 0) +
    p.deps.filter((d) => d.action === "download").length;

  // In-flight "Install & use" calls per family — a ref, not state: a
  // double-click lands inside the same React batch, so state-based guards
  // miss it. The backend registry dedupes downloads, but the second call
  // would still re-plan and toast a spurious "Could not activate" error.
  const usingFamiliesRef = useRef<Set<string>>(new Set());

  const handleUseFamily = async (p: FamilyPlan, variantOverride?: string) => {
    if (usingFamiliesRef.current.has(p.family)) return;
    usingFamiliesRef.current.add(p.family);
    // Take the variant EXPLICITLY when the caller just set one: setVariantPick
    // is async, so reading `variantPick` here synchronously saw the PREVIOUS
    // pick — the GPU-tier buttons installed one quant behind the one they
    // display (first click fetched the default Q4_0 while showing Q6_K).
    const variant = variantOverride ?? pickedVariant(p);
    try {
      const plan = await imageGenUseFamily(p.family, variant);
      const reused = plan.deps.filter((e) => e.action === "use" && e.reused).length;
      const downloaded =
        plan.deps.filter((e) => e.action === "download").length +
        ((plan.variants.find((v) => v.id === variant) ?? plan.variants[0])?.action ===
        "download"
          ? 1 : 0);
      const bits = [
        reused > 0 ? `${reused} existing cop${reused > 1 ? "ies" : "y"} reused` : null,
        downloaded > 0
          ? `${downloaded} download${downloaded > 1 ? "s" : ""} started`
          : null,
      ].filter(Boolean);
      toastSuccess(`${plan.label}: ${bits.join(", ") || "active"}`);
    } catch (err) {
      toastError("Could not activate the package", err);
    } finally {
      usingFamiliesRef.current.delete(p.family);
      void imageGenFamilyPlans().then(setPlans).catch(() => {});
      refresh();
    }
  };

  const detail = status?.catalog.find((m) => m.id === detailId) ?? null;
  const detailDl = detail ? downloads[detail.id] : undefined;
  const detailActive =
    !!detailDl && detailDl.state !== "done" && detailDl.state !== "cancelled" && detailDl.state !== "error";
  const detailPct = detailDl?.total
    ? Math.min(100, Math.round((detailDl.downloaded / detailDl.total) * 100))
    : null;

  return (
    <div className="settings-form">
      <div className="panel-head">
        <h3>Image generation</h3>
      </div>

      <p className="settings-note">
        Local text-to-image on a stable-diffusion.cpp server — open weights, no
        cloud. The agent gets a <code className="mono">generate_image</code> tool
        once an engine build and the models below are installed.
      </p>

      {!status ? (
        <div className="settings-note" style={{ color: "var(--text-dim)" }}>
          Image generation status unavailable (app backend not reachable).
        </div>
      ) : (
        <>
          <div className="settings-note">
            <div style={{ marginBottom: 8 }}>
              {status.running ? (
                <>
                  Server <span style={{ color: "var(--success, #3fb950)" }}>running</span> on
                  port {status.port} —{" "}
                  <code className="mono" style={{ fontSize: 11 }}>
                    {shortName(status.diffusionPath ?? "")}
                  </code>
                </>
              ) : status.binaryPath ? (
                <>
                  Server stopped. Binary:{" "}
                  <code className="mono" style={{ fontSize: 11 }}>
                    {shortName(status.binaryPath)}
                  </code>
                </>
              ) : (
                <span style={{ color: "var(--warn, #d29922)" }}>
                  sd-server binary not found — install an engine build below, or
                  point at an existing build.
                </span>
              )}
            </div>
            <div style={{ display: "flex", justifyContent: "flex-end", marginTop: 8 }}>
              {status.running ? (
                <button className="ghost" style={{ padding: "4px 10px" }} disabled={busy} onClick={() => void handleStop()}>
                  Stop server
                </button>
              ) : (
                <button
                  className="ghost"
                  style={{ padding: "4px 10px" }}
                  disabled={busy || !status.binaryPath}
                  onClick={() => void handleStart()}
                  title={status.defaultModel ? undefined : "Download a diffusion model first"}
                >
                  Start server
                </button>
              )}
            </div>
            {!status.binaryPath && (
              <div style={{ display: "flex", gap: 6, marginTop: 8 }}>
                <input
                  className="mono"
                  style={{ flex: 1, fontSize: 12 }}
                  placeholder="Path to sd-server(.exe) or its containing folder"
                  value={pathInput}
                  onChange={(e) => setPathInput(e.target.value)}
                />
                <button className="ghost" style={{ padding: "4px 10px" }} onClick={() => void handleSavePath()}>
                  Save path
                </button>
              </div>
            )}
          </div>

          {/* Engine builds — one card, three managed rows (CUDA / Vulkan /
              CPU), same harness-style treatment as the speech builds. */}
          <ServerBuildsCard
            ids={["image-sd-cuda", "image-sd-vulkan", "image-sd-cpu"]}
            onInstalled={refresh}
          />

          <div className="settings-note" style={{ marginTop: 4 }}>
            <div style={{ fontSize: 12, fontWeight: 600, marginBottom: 8 }}>Device</div>
            {/* Same segmented control the speech direction switch uses
                (settings-subtabs ships its own active styling). */}
            <div className="settings-subtabs" role="tablist" aria-label="Image generation device">
              {DEVICES.map((d) => (
                <button
                  key={d.id}
                  type="button"
                  role="tab"
                  aria-selected={status.device === d.id}
                  className={`settings-subtab${status.device === d.id ? " active" : ""}`}
                  onClick={() => void handleDevice(d.id)}
                >
                  {d.label}
                </button>
              ))}
            </div>
            <div style={{ fontSize: 11, color: "var(--text-dim)", marginTop: 6 }}>
              {status.device === "auto"
                ? "Auto picks the CUDA build on NVIDIA GPUs, Vulkan on AMD/Intel, and falls back to CPU."
                : status.device === "vulkan"
                  ? status.vulkanAvailable
                    ? "Image generation runs on the Vulkan build — works across NVIDIA, AMD and Intel GPUs."
                    : "No Vulkan build installed yet — install it above; until then Auto/CPU builds are used."
                  : status.cpuAvailable
                    ? "Image generation runs on the CPU build — works everywhere, but a 1024px image takes minutes."
                    : "No CPU build installed yet — install it above, or use Auto."}
            </div>
          </div>

          {/* Model PACKAGES — a family is the whole pipeline (diffusion with
              its quant variants + text encoder + VAE): one button activates
              every piece already on disk — reusing copies that belong to
              other packages or were dropped in by hand — and downloads only
              what is genuinely missing. Detected single files get their own
              one-click cards underneath. */}
          {plans.length > 0 && (
            <div className="settings-note" style={{ marginTop: 4 }}>
              <div style={{ fontWeight: 600, marginBottom: 2 }}>Model packages</div>
              <div style={{ fontSize: 11, color: "var(--text-dim)", marginBottom: 10 }}>
                One click sets up the whole pipeline. Components shared between
                packages — and any matching file already in your models folder —
                are reused, not downloaded twice.
              </div>

              {/* One best per GPU tier: click = activate (downloading what's
                  missing). VRAM figures are the model's comfortable floor. */}
              <div
                className="mono"
                style={{ fontSize: 10, color: "var(--text-dim)", textTransform: "uppercase", letterSpacing: 0.4, marginBottom: 6 }}
              >
                best for your gpu
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 14 }}>
                {GPU_TIERS.map((t) => {
                  const plan = plans.find((pl) => pl.family === t.family);
                  const missing = plan ? planMissing(plan) : 0;
                  return (
                    <button
                      key={t.range}
                      type="button"
                      className="ghost"
                      style={{ padding: "3px 10px", display: "inline-flex", alignItems: "center", gap: 6 }}
                      disabled={!plan}
                      title={plan ? `Install & use ${plan.label} for GPUs with ${t.range} VRAM` : ""}
                      onClick={() => {
                        if (!plan) return;
                        if (t.variant) setVariantPick((prev) => ({ ...prev, [plan.family]: t.variant! }));
                        // Pass the pick EXPLICITLY — the state update above
                        // hasn't landed yet (see handleUseFamily).
                        void handleUseFamily(plan, t.variant);
                      }}
                    >
                      <span style={{ fontWeight: 600 }}>{t.range}</span>
                      <span style={{ color: "var(--text-dim)" }}>→ {t.short}</span>
                      {plan && !plan.active && missing > 0 && (
                        <span
                          className="mono"
                          style={{ fontSize: 9, color: "var(--warn, #d29922)" }}
                        >
                          ↓{missing}
                        </span>
                      )}
                    </button>
                  );
                })}
              </div>

              <div className="theme-gallery-grid" style={{ marginBottom: 4 }}>
                {plans.map((p) => {
                  const picked = pickedEntry(p);
                  const missing = planMissing(p);
                  const isDisk = p.family.startsWith("disk:");
                  const shortName =
                    FAMILY_LABELS[p.family] ??
                    p.label.replace(/\.(gguf|safetensors)$/i, "");
                  const active = p.active;
                  return (
                    <div
                      key={p.family}
                      className={`theme-card${active ? " active" : ""}`}
                      style={{ cursor: "default" }}
                      title={p.label}
                    >
                      {(() => {
                        const src = sampleFor(p.family, p.label);
                        return src ? (
                          <div className="pkg-sample">
                            <img src={src} alt="" loading="lazy" />
                          </div>
                        ) : (
                          <div className="theme-card-swatches">
                            {(FAMILY_SWATCHES.disk).map((c) => (
                              <span key={c} style={{ background: c }} />
                            ))}
                          </div>
                        );
                      })()}
                      <div className="theme-card-name" title={p.label}>
                        {shortName}
                        <span className="theme-card-base">{p.layout}</span>
                      </div>
                      <div style={{ fontSize: 10, color: "var(--text-dim)", marginTop: 2 }}>
                        {picked?.action === "download"
                          ? `${formatBytes(picked.sizeBytes)} download`
                          : `on disk${picked ? ` · ${formatBytes(picked.sizeBytes)}` : ""}`}
                        {p.deps.some((d) => d.action === "download") &&
                          ` + ${p.deps.filter((d) => d.action === "download").length} component${p.deps.filter((d) => d.action === "download").length > 1 ? "s" : ""}`}
                      </div>

                      {/* Quant picker for multi-build split families. */}
                      {p.variants.length > 1 && (
                        <div className="settings-subtabs" role="tablist" style={{ marginTop: 6 }}>
                          {p.variants.map((v) => (
                            <button
                              key={v.id}
                              type="button"
                              role="tab"
                              aria-selected={v.id === picked?.id}
                              className={`settings-subtab${v.id === picked?.id ? " active" : ""}`}
                              style={{ fontSize: 10, padding: "1px 7px" }}
                              title={`${v.label} — ${v.action === "use" ? "on disk" : `download ${formatBytes(v.sizeBytes)}`}`}
                              onClick={() =>
                                setVariantPick((prev) => ({ ...prev, [p.family]: v.id }))
                              }
                            >
                              {v.label.match(/\(([^)]+)\)/)?.[1] ?? v.label}
                              {v.action === "use" ? " ✓" : ""}
                            </button>
                          ))}
                        </div>
                      )}
                      {isDisk && p.layout === "split" && p.deps.some((d) => d.action === "download") && (
                        <div style={{ fontSize: 10, color: "var(--warn, #d29922)", marginTop: 4 }}>
                          missing encoder/VAE — Install &amp; use will download them
                        </div>
                      )}

                      <div className="theme-card-actions">
                        {active ? (
                          <span className="fit-badge fits">✓ Active</span>
                        ) : (
                          <button
                            type="button"
                            className="ghost"
                            style={{ padding: "2px 10px" }}
                            onClick={() => void handleUseFamily(p)}
                            title={
                              isDisk
                                ? "Make this model the default diffusion"
                                : missing > 0
                                  ? `${missing} file${missing > 1 ? "s" : ""} will download; the rest is activated now`
                                  : "Activate all components of this package"
                            }
                          >
                            {!isDisk && missing > 0
                              ? `Install & use (${missing})`
                              : "Use"}
                          </button>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Model groups — everything of a kind in one list (catalog
              downloads AND files found on disk), pick the default per group. */}
          {[
            {
              role: "diffusion" as ImageModelRole,
              title: "Diffusion models",
              hint: "The model that paints. Full checkpoints (SD 1.5 / SDXL) load alone; split models also need one text encoder and one VAE from the groups below.",
              selectLabel: "Set default",
              selectedLabel: "✓ Default",
              rows: diffusionRows,
              empty: "No diffusion model yet — download one or move a file here with the kind dropdown.",
            },
            {
              role: "text-encoder" as ImageModelRole,
              title: "Text encoders",
              hint: "Needed by split models (Z-Image & friends). Nothing selected = the catalog encoder, wherever it sits.",
              selectLabel: "Use",
              selectedLabel: "✓ In use",
              rows: encoderRows,
              empty: "No text encoder — split models can't start. Download the catalog one or move a file here.",
            },
            {
              role: "vae" as ImageModelRole,
              title: "VAE",
              hint: "Decodes the latent into a PNG. Needed by split models. Nothing selected = the catalog VAE.",
              selectLabel: "Use",
              selectedLabel: "✓ In use",
              rows: vaeRows,
              empty: "No VAE — split models can't start. Download the catalog one or move a file here.",
            },
          ].map((group) => (
            <div className="settings-note" style={{ marginTop: 4 }} key={group.role}>
              <div style={{ fontWeight: 600, marginBottom: 2 }}>{group.title}</div>
              <div style={{ fontSize: 11, color: "var(--text-dim)", marginBottom: 8 }}>{group.hint}</div>
              {group.rows.length === 0 ? (
                <div style={{ fontSize: 11, color: "var(--warn, #d29922)" }}>{group.empty}</div>
              ) : (
                <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                  {group.rows.map((r) => {
                    const dl = r.download ? downloads[r.download.id] : undefined;
                    const active =
                      !!dl && dl.state !== "done" && dl.state !== "cancelled" && dl.state !== "error";
                    const pct = dl?.total
                      ? Math.min(100, Math.round((dl.downloaded / dl.total) * 100))
                      : null;
                    return (
                      <div
                        key={r.key}
                        role={r.source === "catalog" ? "button" : undefined}
                        tabIndex={r.source === "catalog" ? 0 : undefined}
                        className="ghost knowledge-suggestion"
                        style={{ cursor: r.source === "catalog" ? undefined : "default" }}
                        onClick={() => {
                          if (r.source === "catalog") setDetailId(r.download?.id ?? null);
                        }}
                        onKeyDown={(e) => {
                          if (r.source === "catalog" && (e.key === "Enter" || e.key === " ")) {
                            e.preventDefault();
                            setDetailId(r.download?.id ?? null);
                          }
                        }}
                        title={r.source === "catalog" ? `View details for ${r.name}` : undefined}
                      >
                        <span className="knowledge-suggestion-main">
                          <span style={{ fontSize: 12, fontWeight: 600 }}>
                            {r.name}
                            {r.selected && (
                              <span className="fit-badge fits" style={{ marginLeft: 8 }}>
                                {group.selectedLabel}
                              </span>
                            )}
                            {r.recommended && !r.selected && !r.installed && (
                              <span className="fit-badge fits" style={{ marginLeft: 8 }}>
                                Recommended
                              </span>
                            )}
                          </span>
                          <span style={{ fontSize: 11, color: "var(--text-dim)" }}>{r.sub}</span>
                        </span>
                        <span
                          style={{
                            display: "inline-flex",
                            alignItems: "center",
                            gap: 10,
                            flexShrink: 0,
                          }}
                        >
                          {/* Manual rows: move between groups (drives which
                              list a file appears in; the guess is editable). */}
                          {r.manual && (
                            <select
                              className="mono"
                              style={{ fontSize: 11, padding: "2px 4px" }}
                              value={r.manual.role}
                              aria-label={`Kind of ${r.name}`}
                              onClick={(e) => e.stopPropagation()}
                              onChange={(e) =>
                                void handleFileRole(r.path, e.target.value as ImageModelRole)
                              }
                            >
                              <option value="diffusion">diffusion</option>
                              <option value="text-encoder">text encoder</option>
                              <option value="vae">VAE</option>
                            </select>
                          )}
                          {/* Diffusion rows: layout. Catalog entries know
                              their own; manual files guess + sniff, with the
                              toggle as the correction. */}
                          {group.role === "diffusion" &&
                            r.layout &&
                            (r.source === "manual" ? (
                              <div
                                className="settings-subtabs"
                                role="group"
                                aria-label={`Layout for ${r.name}`}
                              >
                                {(["full", "split"] as ImageLayout[]).map((l) => (
                                  <button
                                    key={l}
                                    type="button"
                                    role="tab"
                                    aria-selected={r.layout === l}
                                    className={`settings-subtab${r.layout === l ? " active" : ""}`}
                                    title={
                                      l === "full"
                                        ? "Self-contained checkpoint (SD1.5/SDXL-style) — loads alone"
                                        : "Needs the text encoder + VAE groups (Z-Image-style)"
                                    }
                                    onClick={(e) => {
                                      e.stopPropagation();
                                      void handleFileLayout(r.path, l);
                                    }}
                                  >
                                    {l}
                                  </button>
                                ))}
                              </div>
                            ) : (
                              <span
                                className="mono"
                                style={{ fontSize: 10, color: "var(--text-dim)" }}
                                title={
                                  r.layout === "full"
                                    ? "Self-contained checkpoint — loads alone"
                                    : "Split model — uses the encoder + VAE groups"
                                }
                              >
                                {r.layout}
                              </span>
                            ))}
                          <span className="knowledge-suggestion-size mono">
                            {formatBytes(r.sizeBytes)}
                          </span>
                          {!r.installed && active ? (
                            <span style={{ fontSize: 11, color: "var(--text-dim)" }}>
                              {pct !== null ? `${pct}%` : "downloading…"}
                            </span>
                          ) : r.selected ? (
                            <span className="fit-badge fits">✓</span>
                          ) : !r.installed && r.download ? (
                            <button
                              type="button"
                              className="ghost"
                              style={{ padding: "2px 10px" }}
                              onClick={(e) => {
                                e.stopPropagation();
                                handleDownload(r.download!);
                              }}
                            >
                              Download
                            </button>
                          ) : group.role === "diffusion" ? (
                            <button
                              type="button"
                              className="ghost"
                              style={{ padding: "2px 10px" }}
                              onClick={(e) => {
                                e.stopPropagation();
                                void handleSetDefault(r.path, r.layout ?? "split", r.name);
                              }}
                            >
                              {group.selectLabel}
                            </button>
                          ) : (
                            <button
                              type="button"
                              className="ghost"
                              style={{ padding: "2px 10px" }}
                              onClick={(e) => {
                                e.stopPropagation();
                                // Selecting the CATALOG file = back to
                                // automatic (it's the default anyway).
                                void handleSelect(
                                  group.role as "text-encoder" | "vae",
                                  r.source === "manual" ? r.path : null,
                                );
                              }}
                            >
                              {group.selectLabel}
                            </button>
                          )}
                        </span>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          ))}

          <div className="settings-note" style={{ marginTop: 4 }}>
            <div style={{ fontWeight: 600, marginBottom: 8 }}>Try it</div>
            {!status.running ? (
              <div style={{ fontSize: 11, color: "var(--text-dim)" }}>
                Start the server above to generate a test image here.
              </div>
            ) : (
              <>
                <div style={{ display: "flex", gap: 6 }}>
                  <input
                    style={{ flex: 1, fontSize: 12 }}
                    placeholder="a red fox curled on mossy ground at dawn, soft mist"
                    value={tryPrompt}
                    onChange={(e) => setTryPrompt(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === "Enter" && !busy) void handleTry();
                    }}
                  />
                  <button
                    className="ghost"
                    style={{ padding: "4px 12px" }}
                    disabled={busy || !tryPrompt.trim()}
                    onClick={() => void handleTry()}
                  >
                    {busy ? "Generating…" : "Generate"}
                  </button>
                </div>
                {busy && (
                  <div style={{ fontSize: 11, color: "var(--text-dim)", marginTop: 8 }}>
                    Rendering — the first image after a cold start takes longer
                    (the GPU compiles its kernels once).
                  </div>
                )}
                {tryImage && (
                  <div style={{ marginTop: 10 }}>
                    <img
                      src={tryImage.dataUri}
                      alt={tryPrompt}
                      style={{ maxWidth: "100%", borderRadius: 8, display: "block" }}
                    />
                    <div style={{ fontSize: 11, color: "var(--text-dim)", marginTop: 4 }}>
                      {tryImage.width}×{tryImage.height} — the agent produces the
                      same thing with the generate_image tool.
                    </div>
                  </div>
                )}
              </>
            )}
          </div>
        </>
      )}

      {/* Detail modal — rendered ONLY when a model is selected (see the note
          in SttPanel about Modal having no internal open state). */}
      {detail && (
        <Modal
          title={detail.label}
          onClose={() => setDetailId(null)}
          actions={
            detail.installed ? (
              detail.isDefault ? (
                <div className="model-card-status done" style={{ margin: 0, flex: 1, textAlign: "center" }}>
                  ✓ Installed — default image model
                </div>
              ) : detail.role === "diffusion" ? (
                <button
                  className="primary cta-strong"
                  style={{ flex: 1 }}
                  onClick={() => void handleSetDefault(`image-gen/${detail.filename}`, detail.layout, detail.label)}
                >
                  Set as default image model
                </button>
              ) : (
                <div className="model-card-status done" style={{ margin: 0, flex: 1, textAlign: "center" }}>
                  ✓ Installed
                </div>
              )
            ) : detailActive ? (
              <button className="ghost" onClick={() => void cancelModelDownload(detail.id)} style={{ flex: 1 }}>
                Cancel download{detailPct !== null ? ` (${detailPct}%)` : ""}
              </button>
            ) : (
              <button
                className="primary cta-strong"
                style={{ flex: 1 }}
                onClick={() => handleDownload(detail)}
              >
                Download ({formatBytes(detail.sizeBytes)})
              </button>
            )
          }
        >
          <div className="model-detail-modal">
            <div className="model-detail-hero">
              <div className="model-detail-avatar-lg">I</div>
              <div>
                <div className="model-detail-repo">{detail.filename}</div>
                <div className="model-detail-stats">
                  <span>{formatBytes(detail.sizeBytes)}</span>
                  <span>·</span>
                  <span>{detail.role === "diffusion" ? "diffusion model (GGUF)" : detail.role === "text-encoder" ? "text encoder (GGUF)" : "VAE (safetensors)"}</span>
                </div>
              </div>
            </div>
            <p className="model-detail-desc">
              {detail.note}. Downloads run through the app's model engine into{" "}
              <code className="mono">{status?.imageDir ?? "<models>/image-gen"}</code>.
            </p>
            {detailActive && (
              <div className="model-market-grid">
                <div className="model-card-progress" style={{ padding: 0 }}>
                  <div className="model-card-progress-bar">
                    <div className="model-card-progress-fill" style={{ width: `${detailPct ?? 0}%` }} />
                  </div>
                  <div className="model-card-progress-info">
                    <span>
                      {detailPct !== null ? `${detailPct}% · ` : ""}
                      {formatBytes(detailDl?.downloaded ?? 0)}
                      {detailDl?.total ? ` / ${formatBytes(detailDl.total)}` : ""}
                    </span>
                  </div>
                </div>
              </div>
            )}
          </div>
        </Modal>
      )}
    </div>
  );
}
